// 补充 api/tableau.ts 未导出的类型

export interface FieldSemantic {
  field?: string;
  name?: string;
  caption?: string;
  role?: string;
  data_type?: string;
  dataType?: string;
  meaning?: string;
  description?: string;
  aggregation?: string | null;
  formula?: string | null;
  fully_qualified_name?: string;
  fullyQualifiedName?: string;
  is_hidden?: boolean;
  isHidden?: boolean;
  source?: string;
  source_label?: string;
  cached?: boolean;
  updated_at?: string | null;
  fetched_at?: string | null;
  mcp?: FieldMcpMetadata | null;
}

export interface FieldMcpMetadata {
  columnClass?: string | null;
  logicalTableId?: string | null;
  dataCategory?: string | null;
  defaultAggregation?: string | null;
  defaultFormat?: string | null;
  formula?: string | null;
  isAutoGenerated?: boolean | null;
  hasUserReference?: boolean | null;
  isHidden?: boolean | null;
  fullyQualifiedName?: string | null;
  role?: string | null;
  dataType?: string | null;
}

export interface FieldMetadataStatus {
  field_count?: number | null;
  local_field_count?: number | null;
  cache_status?: string | null;
  cached_at?: string | null;
  updated_at?: string | null;
}
