"""
Tableau MCP 查询客户端（Stage 3 执行层）— T-R1 重写

PRD §5.5 契约实现：
- 约束 A：环境变量完整性（PAT 解密后注入）→ 移至 MCP server 进程 env（已由官方 server 持有）
- 约束 B：MCP ClientSession 长连接复用（单例模式）→ 重写为 streamable-http + session-id 管理
- 约束 C：VizQL JSON 与字段元数据一致性校验
- 约束 D（新增 P0）：connection_id 贯穿上下文，禁止跨租户 client 缓存

MCP Server 通信：标准 MCP Streamable-HTTP over JSON-RPC 2.0
协议参考：https://modelcontextprotocol.io/specification/2025-06-18
工具实现：@tableau/mcp-server@1.18.1

T-R1 变更摘要：
- 删除自定义 REST 传输（`POST /query-datasource` + `env` 注入）
- 改为标准 MCP 传输：`initialize` → `notifications/initialized` → `tools/call`
- 新增模块级 MCP session 生命周期管理（session-id header、过期重建、DELETE 释放）
- 新增 SSE 解析（`event: message\ndata: {...}`）
- 保留：per-connection_id 实例缓存、contextvars 隔离、OOM 防护、idle 清理、错误码映射
"""
import contextvars
import json
import logging
import threading
import time
import uuid
from typing import Any, Dict, Iterable, Optional

import requests

from app.core.crypto import get_tableau_crypto
from services.common.settings import (
    get_tableau_mcp_server_url,
    get_tableau_mcp_protocol_version,
)
from services.tableau.models import TableauConnection, TableauAsset, TableauDatabase


_MCP_FIELD_METADATA_KEYS = (
    "name",
    "dataType",
    "role",
    "columnClass",
    "logicalTableId",
    "defaultAggregation",
    "dataCategory",
    "formula",
    "defaultFormat",
    "isAutoGenerated",
    "hasUserReference",
    "isHidden",
    "fullyQualifiedName",
)


class _CachedTableauConnection:
    """
    TableauConnection 脱管缓存对象。

    仅保存查询得到的必要属性（原始 Python 类型），不持有 SQLAlchemy Session 引用。
    用于在 Session 关闭后安全访问连接属性，防止 DetachedInstanceError。
    """

    __slots__ = (
        "id", "server_url", "site", "token_name", "token_encrypted",
        "is_active", "last_test_success", "mcp_direct_enabled", "mcp_server_url",
        "mcp_server_id", "mcp_binding_status",
    )

    def __init__(
        self,
        id: int,
        server_url: str,
        site: str,
        token_name: str,
        token_encrypted: str,
        is_active: bool,
        last_test_success: bool,
        mcp_direct_enabled: bool = False,
        mcp_server_url: str = None,
        mcp_server_id: Optional[int] = None,
        mcp_binding_status: Optional[str] = None,
    ):
        self.id = id
        self.server_url = server_url
        self.site = site
        self.token_name = token_name
        self.token_encrypted = token_encrypted
        self.is_active = is_active
        self.last_test_success = last_test_success
        self.mcp_direct_enabled = mcp_direct_enabled
        self.mcp_server_url = mcp_server_url
        self.mcp_server_id = mcp_server_id
        self.mcp_binding_status = mcp_binding_status


logger = logging.getLogger(__name__)

_MULAN_MCP_TIMEOUT_HEADER = "X-Mulan-MCP-Timeout"
_QUERY_RETRY_BUDGET_SECONDS = 10.0
_TRANSPORT_RETRY_MAX_ATTEMPTS = 3
_READ_TIMEOUT_RETRY_MAX_ATTEMPTS = 2
_RETRY_BACKOFF_SECONDS = (0.5, 1.5)
_MIN_RETRY_REMAINING_SECONDS = 1.0
MCP_NL_TOOL_UNAVAILABLE = "MCP_NL_TOOL_UNAVAILABLE"
_STRUCTURED_QUERY_DATASOURCE_TOOL_NAMES = frozenset({"query-datasource"})
_DEFAULT_NL_QUERY_TOOL_NAMES = (
    "query-datasource-nl",
    "query-datasource-natural-language",
    "natural-language-query-datasource",
    "ask-datasource",
    "ask-data-source",
)
_NL_QUESTION_ARGUMENT_NAMES = (
    "question",
    "naturalLanguageQuery",
    "natural_language_query",
    "queryText",
    "query_text",
    "query",
    "message",
    "prompt",
)
_NL_DATASOURCE_ARGUMENT_NAMES = (
    "datasourceLuid",
    "dataSourceLuid",
    "datasource_luid",
    "datasourceId",
    "datasource_id",
    "datasourceIdentifier",
    "datasource_identifier",
)
_NL_LIMIT_ARGUMENT_NAMES = ("limit", "rowLimit", "row_limit")


def extract_datasource_metadata_fields(raw: Any) -> list[Dict[str, Any]]:
    """Extract Tableau MCP datasource fields from all observed response shapes."""
    if not isinstance(raw, dict):
        return []

    candidates: list[Any] = []
    candidates.append(raw.get("fields"))

    nested_raw = raw.get("raw")
    if isinstance(nested_raw, dict):
        candidates.append(nested_raw.get("fields"))
        candidates.append(_fields_from_groups(nested_raw.get("fieldGroups")))

    candidates.append(_fields_from_groups(raw.get("fieldGroups")))

    fields: list[Dict[str, Any]] = []
    seen: set[str] = set()
    for candidate in candidates:
        if not isinstance(candidate, list):
            continue
        for item in candidate:
            if not isinstance(item, dict):
                continue
            key = (
                str(item.get("name") or item.get("fieldName") or item.get("fieldCaption") or ""),
                str(item.get("logicalTableId") or item.get("fullyQualifiedName") or ""),
            )
            if key in seen:
                continue
            seen.add(key)
            fields.append(item)
    return fields


def _fields_from_groups(groups: Any) -> list[Dict[str, Any]]:
    if not isinstance(groups, list):
        return []
    fields: list[Dict[str, Any]] = []
    for group in groups:
        if not isinstance(group, dict):
            continue
        group_fields = group.get("fields")
        if not isinstance(group_fields, list):
            continue
        for field in group_fields:
            if isinstance(field, dict):
                fields.append(field)
    return fields


def normalize_datasource_metadata_field(field: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize one Tableau MCP field for DB cache storage."""
    field_name = field.get("fieldName") or field.get("name") or field.get("fieldCaption") or ""
    field_caption = field.get("fieldCaption") or field.get("caption") or ""
    data_type = field.get("dataType") or field.get("data_type") or field.get("type") or "STRING"
    role = field.get("role") or field.get("semanticRole") or "dimension"
    role = str(role).lower()
    aggregation = field.get("aggregation") or field.get("defaultAggregation")
    formula = field.get("formula")
    column_class = str(field.get("columnClass") or "").upper()
    is_calculated = bool(field.get("isCalculated") or field.get("is_calculated") or formula or column_class == "CALCULATION")

    metadata_json = dict(field)
    for key in _MCP_FIELD_METADATA_KEYS:
        metadata_json.setdefault(key, field.get(key))

    return {
        "field_name": str(field_name),
        "field_caption": str(field_caption) if field_caption is not None else "",
        "data_type": str(data_type) if data_type is not None else "STRING",
        "role": role if role in ("measure", "dimension") else role,
        "description": field.get("description") or "",
        "formula": formula,
        "aggregation": aggregation,
        "is_calculated": is_calculated,
        "metadata_json": metadata_json,
    }

# ─────────────────────────────────────────────────────────────────────────────
# connection_id 上下文变量（约束 D：跨协程传递租户上下文）
# ─────────────────────────────────────────────────────────────────────────────
_connection_id_var: contextvars.ContextVar[Optional[int]] = contextvars.ContextVar(
    "tableau_mcp_connection_id", default=None
)
_user_id_var: contextvars.ContextVar[Optional[int]] = contextvars.ContextVar(
    "tableau_mcp_user_id", default=None
)
_trace_id_var: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "tableau_mcp_trace_id", default=None
)


def set_mcp_connection_id(connection_id: int) -> None:
    """在当前上下文设置 connection_id（由调用方在发起 MCP 请求前调用）"""
    _connection_id_var.set(connection_id)


def get_mcp_connection_id() -> Optional[int]:
    """获取当前上下文的 connection_id"""
    return _connection_id_var.get()


def set_mcp_runtime_context(
    *,
    connection_id: Optional[int] = None,
    user_id: Optional[int] = None,
    trace_id: Optional[str] = None,
) -> None:
    if connection_id is not None:
        _connection_id_var.set(connection_id)
    if user_id is not None:
        _user_id_var.set(user_id)
    if trace_id is not None:
        _trace_id_var.set(trace_id)


# ─────────────────────────────────────────────────────────────────────────────
# 模块级 HTTP Session 管理（约束 B：连接池复用）
# ─────────────────────────────────────────────────────────────────────────────

_http_session_lock = threading.Lock()
_http_session: Optional[requests.Session] = None


def _get_http_session() -> requests.Session:
    """获取共享的 requests.Session（单例）。"""
    global _http_session
    if _http_session is None:
        with _http_session_lock:
            if _http_session is None:
                s = requests.Session()
                adapter = requests.adapters.HTTPAdapter(
                    pool_connections=10,
                    pool_maxsize=20,
                    max_retries=0,  # 重试由 TableauMCPClient 按错误分类和总预算控制
                )
                s.mount("http://", adapter)
                s.mount("https://", adapter)
                _http_session = s
    return _http_session


# ─────────────────────────────────────────────────────────────────────────────
# 模块级 MCP Session 状态（进程级共享，MVP 单 Tableau Site）
# ─────────────────────────────────────────────────────────────────────────────

class _MCPSessionState:
    """
    MCP session 生命周期状态。

    MVP 约束：所有 connection_id 共享同一个 MCP server 进程，
    因此 session 是进程级共享资源（非 per-connection_id）。
    多租户场景（P2+）改造成 {site → _MCPSessionState} 映射。
    """

    def __init__(self) -> None:
        self.lock = threading.Lock()
        self.session_id: Optional[str] = None
        self.last_activity: float = 0.0
        self.last_used: float = time.monotonic()  # LRU 驱逐用（P1）
        self.protocol_version: str = "2025-06-18"
        self._initialized = False

    def reset(self) -> None:
        with self.lock:
            self.session_id = None
            self.last_activity = 0.0
            self._initialized = False


# ─────────────────────────────────────────────────────────────────────────────
# 多站点 MCP Session 状态（P0 改造：per-site 隔离）
# ─────────────────────────────────────────────────────────────────────────────

_mcp_session_states: Dict[str, _MCPSessionState] = {}
_mcp_session_states_lock = threading.Lock()

# 向后兼容别名：原有模块级单例，指向默认站点状态（懒创建）
# 内部函数通过 _get_or_create_session_state 获取正确实例
_mcp_session_state = _MCPSessionState()  # 保留用于向后兼容（_invalidate_session 等）


def _get_site_key(conn) -> str:
    """返回站点唯一键：{server_url}|{site}"""
    server_url = getattr(conn, "server_url", "") or ""
    site = getattr(conn, "site", "") or ""
    return f"{server_url}|{site}"


def _load_active_tableau_mcp_binding(connection_id: Optional[int]) -> Optional[dict]:
    if not isinstance(connection_id, int):
        return None
    try:
        from app.core.database import SessionLocal
        from services.mcp.models import McpServer

        session = SessionLocal()
        try:
            binding = (
                session.query(McpServer)
                .filter(
                    McpServer.type == "tableau",
                    McpServer.tableau_connection_id == connection_id,
                    McpServer.is_active == True,
                )
                .order_by(McpServer.updated_at.desc(), McpServer.id.desc())
                .first()
            )
            if not binding:
                return None
            return {
                "mcp_server_id": binding.id,
                "mcp_server_url": binding.server_url,
                "mcp_binding_status": binding.binding_status,
            }
        finally:
            session.close()
    except Exception as exc:
        logger.warning("Failed to load Tableau MCP binding for connection_id=%s: %s", connection_id, exc)
        return None


def _get_effective_mcp_base_url(conn) -> Optional[str]:
    """Return a configured MCP endpoint, ignoring accidental Tableau server URLs.

    Some records were backfilled with mcp_server_url equal to server_url
    (for example https://bi.ksyun.com). That is a Tableau site root, not an MCP
    streamable-http endpoint, and initialize returns 200 without mcp-session-id.
    In that case fall back to TABLEAU_MCP_SERVER_URL.
    """
    binding = _load_active_tableau_mcp_binding(getattr(conn, "id", None))
    if binding and binding.get("mcp_server_url"):
        return str(binding["mcp_server_url"]).strip().rstrip("/")

    raw_mcp_url = getattr(conn, "mcp_server_url", None)
    raw_server_url = getattr(conn, "server_url", None)
    mcp_url = raw_mcp_url.strip() if isinstance(raw_mcp_url, str) else ""
    server_url = raw_server_url.strip() if isinstance(raw_server_url, str) else ""
    if not mcp_url:
        return None
    if server_url and mcp_url.rstrip("/") == server_url.rstrip("/"):
        logger.warning(
            "Ignoring mcp_server_url equal to Tableau server_url; falling back to TABLEAU_MCP_SERVER_URL: %s",
            mcp_url,
        )
        return None
    return mcp_url


def _get_or_create_session_state(site_key: str, _max_sites: int = 50) -> _MCPSessionState:
    """
    获取或创建指定 site_key 的 _MCPSessionState，并实现 LRU 驱逐（P1）。

    参数：
        site_key: 由 _get_site_key(conn) 返回的字符串
        _max_sites: 最大站点数，达到上限时驱逐最久未访问的站点（默认 50）

    线程安全：全部操作在 _mcp_session_states_lock 内进行。

    严格上限强制（Gap 4）：无论 site_key 是否已存在，创建新 entry 前必须检查。
    若超出上限则先驱逐最旧 session 再创建。
    """
    with _mcp_session_states_lock:
        now = time.monotonic()

        # 严格上限检查：当 site_key 不在字典中且池已满时，立即驱逐最旧 session
        if site_key not in _mcp_session_states and len(_mcp_session_states) >= _max_sites:
            oldest_key = min(
                _mcp_session_states.keys(),
                key=lambda k: _mcp_session_states[k].last_used
            )
            oldest_state = _mcp_session_states.pop(oldest_key)
            logger.info(
                "MCP session pool: evicted %s (last_used=%.1fs ago, pool_size=%d)",
                oldest_key,
                now - oldest_state.last_used,
                len(_mcp_session_states) + 1,
            )
            # 释放 MCP session（非阻塞，驱逐过程中不持有 oldest_state.lock）
            try:
                _invalidate_session(session_state=oldest_state)
            except Exception as e:
                logger.warning("MCP session pool evict warning: %s", e)

        if site_key not in _mcp_session_states:
            _mcp_session_states[site_key] = _MCPSessionState()
            logger.debug("_get_or_create_session_state: 创建新 session_state, site_key=%s", site_key)

        state = _mcp_session_states[site_key]
        state.last_used = now  # 每次访问更新 LRU 时间戳
        return state


# ─────────────────────────────────────────────────────────────────────────────
# MCP Session 管理函数
# ─────────────────────────────────────────────────────────────────────────────

_jsonrpc_id_counter = 0
_id_lock = threading.Lock()


def _next_id() -> int:
    """生成自增 JSON-RPC id（线程安全）。"""
    global _jsonrpc_id_counter
    with _id_lock:
        _jsonrpc_id_counter += 1
        return _jsonrpc_id_counter


def _build_headers(
    with_session: bool = True,
    session_state: Optional[_MCPSessionState] = None,
    jwt_token: Optional[str] = None,
    mcp_context: Optional[Dict[str, Any]] = None,
) -> Dict[str, str]:
    """
    构建 MCP HTTP 请求头。

    参数：
        with_session: 是否附加 mcp-session-id
        session_state: 指定 session 状态实例（默认使用全局 _mcp_session_state）
        jwt_token: Tableau Connected Apps JWT（非 None 时注入 Authorization: Bearer，
                   以用户身份发起请求，替代 MCP server 全局 PAT）
    """
    state = session_state if session_state is not None else _mcp_session_state
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json, text/event-stream",
        "MCP-Protocol-Version": state.protocol_version,
    }
    if with_session and state.session_id:
        headers["mcp-session-id"] = state.session_id
    if jwt_token:
        headers["Authorization"] = f"Bearer {jwt_token}"
    if mcp_context:
        headers.update(_build_mulan_headers(mcp_context))
    return headers


def _build_mulan_headers(mcp_context: Dict[str, Any]) -> Dict[str, str]:
    connection_id = mcp_context.get("tableau_connection_id") or mcp_context.get("connection_id")
    mcp_server_id = mcp_context.get("mcp_server_id")
    user_id = mcp_context.get("user_id")
    trace_id = mcp_context.get("trace_id")
    return {
        "X-Mulan-Tableau-Connection-Id": str(connection_id or ""),
        "X-Mulan-Mcp-Server-Id": str(mcp_server_id or ""),
        "X-Mulan-User-Id": str(user_id if user_id is not None else ""),
        "X-Mulan-Trace-Id": str(trace_id or uuid.uuid4()),
    }


def _parse_sse(response_text: str) -> Dict[str, Any]:
    """
    解析 SSE 响应体。

    MCP streamable-http 响应格式：
        event: message
        data: {"jsonrpc":"2.0","id":1,"result":{...}}

    规则：
        1. 按行分割
        2. 找 "data: " 开头的行（注意空格）
        3. 剥前缀，json.loads
        4. 多 data 行时用 \\n 连接（MCP 允许多行；Tableau server 目前单行足够）
    """
    lines = response_text.split("\n")
    data_lines = [
        line[6:] for line in lines
        if line.startswith("data: ")
    ]
    if not data_lines:
        raise TableauMCPError(
            code="NLQ_006",
            message="MCP SSE 响应无 data 字段",
            details={"raw": response_text[:500]},
        )
    payload = "\n".join(data_lines)
    return json.loads(payload)


def _post_mcp(
    payload: Dict[str, Any],
    method: str,
    timeout: int = 30,
    expect_sse: bool = True,
    session_state: Optional[_MCPSessionState] = None,
    base_url: Optional[str] = None,
    jwt_token: Optional[str] = None,
    mcp_context: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    发送 MCP JSON-RPC 请求，返回解析后的响应体。

    参数：
        method: 用于日志的 MCP method 名（如 "initialize"）
        timeout: 请求超时秒数
        expect_sse: 是否解析 SSE 响应（False 用于 initialize 握手）
        session_state: 指定 session 状态实例（默认使用全局 _mcp_session_state）
        base_url: MCP server URL（优先用参数值，fallback 到全局配置）
        jwt_token: Tableau Connected Apps JWT（非 None 时以用户身份发请求，替代全局 PAT）

    重试策略：
        - 网络错误 / 5xx：重试 1 次，间隔 1s
        - 4xx：不重试
        - session 过期（HTTP 400 + "No valid session ID"）：由调用方处理（_ensure_session）
    """
    url = base_url if base_url else get_tableau_mcp_server_url()
    headers = _build_headers(
        with_session=True,
        session_state=session_state,
        jwt_token=jwt_token,
        mcp_context=mcp_context,
    )
    # Keep the gateway-side tool timeout slightly below the HTTP read timeout.
    # Otherwise a client-side timeout can leave the gateway proxy locked until
    # its own longer default timeout expires, making the next ask look hung.
    headers[_MULAN_MCP_TIMEOUT_HEADER] = str(max(1, int(timeout) - 1))
    last_error: Optional[Exception] = None

    for attempt in range(2):
        try:
            resp = _get_http_session().post(
                url,
                json=payload,
                headers=headers,
                timeout=timeout,
            )
            # Session 过期检测：HTTP 400 + "No valid session ID"
            if resp.status_code == 400 and "No valid session ID" in resp.text:
                # 抛出特殊标记，让 _ensure_session 处理
                raise _SessionExpiredError("Session expired or invalid")

            if resp.status_code >= 500 and attempt == 0:
                time.sleep(1)
                continue
            if resp.status_code >= 400:
                raise TableauMCPError(
                    code="NLQ_006",
                    message=f"MCP 请求失败（HTTP {resp.status_code}）",
                    details={"method": method, "status_code": resp.status_code},
                )

            if expect_sse:
                return _parse_sse(resp.text)
            else:
                # initialize 响应也是 SSE，但格式更简单
                try:
                    return _parse_sse(resp.text)
                except (json.JSONDecodeError, TableauMCPError):
                    # 某些 server 实现在 initialize 成功时返回空或纯文本
                    logger.debug("initialize 响应非标准 SSE: %s", resp.text[:200])
                    return {}

        except _SessionExpiredError:
            raise  # 不重试，直接让调用方处理
        except requests.exceptions.ConnectTimeout:
            raise TableauMCPError(
                code="NLQ_006",
                message=f"MCP 连接超时（{timeout}s）",
                details={"method": method, "timeout": timeout, "retry_kind": "transport"},
            )
        except requests.exceptions.ReadTimeout:
            raise TableauMCPError(
                code="NLQ_007",
                message=f"MCP 查询超时（{timeout}s）",
                details={"method": method, "timeout": timeout, "retry_kind": "read_timeout"},
            )
        except requests.exceptions.Timeout:
            raise TableauMCPError(
                code="NLQ_007",
                message=f"MCP 查询超时（{timeout}s）",
                details={"method": method, "timeout": timeout, "retry_kind": "read_timeout"},
            )
        except TableauMCPError:
            raise  # 已构造好，直接透传
        except Exception as e:
            last_error = e
            if attempt == 0:
                time.sleep(1)
                continue
            logger.error("MCP 请求异常（%s）: %s", method, e)

    # 两次尝试均失败
    raise TableauMCPError(
        code="NLQ_006",
        message=f"MCP 服务不可用（{method}）",
        details={"method": method, "error": str(last_error)},
    )


class _SessionExpiredError(Exception):
    """Session 过期标记（不在外层重试，由 _ensure_session 内部重建）"""
    pass


def _ensure_session(
    timeout: int = 30,
    site_key: Optional[str] = None,
    base_url: Optional[str] = None,
    session_state: Optional[_MCPSessionState] = None,
    jwt_token: Optional[str] = None,
    mcp_context: Optional[Dict[str, Any]] = None,
) -> str:
    """
    确保 MCP session 已建立。

    流程：
        1. 若 session 已活跃（last_activity < 5min），直接返回 session_id
        2. 若未初始化或过期，发起 initialize + notifications/initialized
        3. 收到 session 过期 HTTP 400，清空 session_id 后重建

    参数：
        timeout: 超时秒数
        site_key: 站点唯一键（多站点改造，P0 新增）
        base_url: MCP Server URL（优先用参数值，fallback 到全局配置）
        session_state: 指定 session 状态实例（默认使用全局 _mcp_session_state）
        jwt_token: Tableau Connected Apps JWT（非 None 时以用户身份发起握手，替代全局 PAT）

    返回：
        有效的 session_id

    线程安全（自旋锁保护）。
    """
    state = session_state if session_state is not None else _mcp_session_state
    protocol_ver = get_tableau_mcp_protocol_version()
    now = time.monotonic()
    idle_timeout = 300  # 5 分钟，与 _IDLE_TIMEOUT 保持一致
    effective_url = base_url if base_url else get_tableau_mcp_server_url()

    with state.lock:
        # 检查活跃 session
        if (
            state.session_id
            and state._initialized
            and (now - state.last_activity) < idle_timeout
        ):
            return state.session_id

        # 重置状态，触发完整初始化（inline 而非调用 reset() 避免重入锁死锁）
        state.session_id = None
        state.last_activity = 0.0
        state._initialized = False
        state.protocol_version = protocol_ver

    headers_base = {
        "Content-Type": "application/json",
        "Accept": "application/json, text/event-stream",
        "MCP-Protocol-Version": protocol_ver,
    }
    if jwt_token:
        headers_base["Authorization"] = f"Bearer {jwt_token}"
    if mcp_context:
        headers_base.update(_build_mulan_headers(mcp_context))

    # Step 1: initialize
    init_payload = {
        "jsonrpc": "2.0",
        "id": _next_id(),
        "method": "initialize",
        "params": {
            "protocolVersion": protocol_ver,
            "capabilities": {},
            "clientInfo": {
                "name": "mulan-bi-mcp-client",
                "version": "1.0.0",
            },
        },
    }

    resp = _get_http_session().post(
        effective_url,
        json=init_payload,
        headers=headers_base,
        timeout=timeout,
    )

    if resp.status_code == 400 and "No valid session ID" in resp.text:
        raise TableauMCPError(
            code="NLQ_006",
            message="MCP initialize 失败：session 初始化被拒绝",
            details={"status_code": resp.status_code, "body": resp.text[:200]},
        )

    if resp.status_code >= 400:
        raise TableauMCPError(
            code="NLQ_006",
            message=f"MCP initialize 失败（HTTP {resp.status_code}）",
            details={"status_code": resp.status_code},
        )

    # 抽取 session_id 从响应 header
    session_id = None
    for k, v in resp.headers.items():
        if k.lower() == "mcp-session-id":
            session_id = v
            break

    if not session_id:
        # 某些实现可能把 session_id 放 body 里
        try:
            body = json.loads(resp.text)
            session_id = body.get("sessionId") or body.get("session_id")
        except (json.JSONDecodeError, Exception):
            pass

    if not session_id:
        raise TableauMCPError(
            code="NLQ_006",
            message="MCP initialize 成功但响应中无 session-id",
            details={"body": resp.text[:500]},
        )

    # Step 2: notifications/initialized（告知 server 端握手完成）
    notif_payload = {
        "jsonrpc": "2.0",
        "id": _next_id(),
        "method": "notifications/initialized",
        "params": {},
    }
    notif_headers = {
        **headers_base,
        "mcp-session-id": session_id,
    }
    # notifications/initialized 期望 202 Accepted，server 不返回 body
    try:
        notif_resp = _get_http_session().post(
            effective_url,
            json=notif_payload,
            headers=notif_headers,
            timeout=timeout,
        )
        logger.debug("notifications/initialized 响应: %d %s", notif_resp.status_code, notif_resp.text[:200])
    except Exception as e:
        logger.warning("notifications/initialized 失败（不影响主流程）: %s", e)

    # 写入状态
    with state.lock:
        state.session_id = session_id
        state.last_activity = time.monotonic()
        state._initialized = True

    site_info = f" site_key={site_key}" if site_key else ""
    logger.info("MCP session 建立成功，session_id=%s%s", session_id[:16] + "...", site_info)
    return session_id


def _invalidate_session(
    session_state: Optional[_MCPSessionState] = None,
    base_url: Optional[str] = None,
) -> None:
    """
    主动释放 MCP session（发 DELETE，然后清状态）。

    参数：
        session_state: 指定 session 状态实例（默认使用全局 _mcp_session_state）
        base_url: MCP Server URL（优先用参数值，fallback 到全局配置）
    """
    state = session_state if session_state is not None else _mcp_session_state
    session_id = state.session_id
    if not session_id:
        state.reset()
        return

    effective_url = base_url if base_url else get_tableau_mcp_server_url()
    headers = _build_headers(with_session=True, session_state=state)

    try:
        resp = _get_http_session().delete(
            effective_url,
            headers=headers,
            timeout=10,
        )
        logger.debug("MCP DELETE session 响应: %d %s", resp.status_code, resp.text[:200])
    except Exception as e:
        logger.warning("MCP DELETE session 失败（非致命）: %s", e)
    finally:
        state.reset()


# ─────────────────────────────────────────────────────────────────────────────
# Tableau MCP Client
# ─────────────────────────────────────────────────────────────────────────────

class TableauMCPError(Exception):
    """Tableau MCP 查询异常"""
    def __init__(self, code: str, message: str, details: dict = None):
        self.code = code
        self.message = message
        self.details = details or {}
        super().__init__(f"[{code}] {message}")


class TableauMCPClient:
    """
    Tableau MCP 查询客户端（per-user session 模式，T-R1 架构决策）。

    核心 invariant：每个 (username, connection_id) 组合对应唯一 client 实例，
    禁止跨用户共享（防止高并发下数据串签）。LRU 容量 50，与 Spec 14 §V2 保持一致。

    使用方式：
        client = get_tableau_mcp_client(username="alice", connection_id=conn_id)
        result = client.query_datasource(datasource_luid, vizql_json, connection_id=conn_id, timeout=30)

    T-R1 变更：传输层从自定义 REST 改为标准 MCP streamable-http。
    MCP session 是进程级共享资源（所有用户共用，按 site_key 隔离）。
    client 对象按 (username, connection_id) 隔离，确保 _ds_connection_cache 不跨用户混用。
    """

    # 按 (username, connection_id) 隔离的 client 实例缓存（LRU 容量 50）
    _instances: Dict[tuple, "TableauMCPClient"] = {}
    _instances_lock = threading.Lock()
    _MAX_INSTANCES = 50   # per-user LRU 容量，与 Spec 14 §V2 保持一致
    _IDLE_TIMEOUT = 300   # 5 分钟空闲超时
    _last_access: Dict[tuple, float] = {}

    @classmethod
    def cleanup_idle(cls) -> int:
        """清理空闲超过 _IDLE_TIMEOUT 的实例。返回清理数量。"""
        now = time.monotonic()
        removed = 0
        with cls._instances_lock:
            expired = [
                key for key, ts in cls._last_access.items()
                if now - ts > cls._IDLE_TIMEOUT
            ]
            for key in expired:
                cls._instances.pop(key, None)
                cls._last_access.pop(key, None)
                removed += 1
        if removed:
            logger.info("cleanup_idle: 清理 %d 个空闲 MCP client 实例", removed)
        return removed

    @classmethod
    def invalidate(cls, connection_id: int, username: Optional[str] = None) -> None:
        """
        主动失效指定连接的 client 实例。

        若指定 username，只清除该用户的实例；否则清除该 connection_id 下所有用户实例。
        """
        with cls._instances_lock:
            if username is not None:
                key = (username, connection_id)
                cls._instances.pop(key, None)
                cls._last_access.pop(key, None)
            else:
                # 清除该 connection_id 下所有用户实例
                keys_to_remove = [k for k in cls._instances if k[1] == connection_id]
                for k in keys_to_remove:
                    cls._instances.pop(k, None)
                    cls._last_access.pop(k, None)

    def __new__(cls, connection_id: int, username: str = "") -> "TableauMCPClient":
        cache_key = (username, connection_id)
        with cls._instances_lock:
            now = time.monotonic()
            # 空闲清理
            expired = [
                k for k, ts in cls._last_access.items()
                if now - ts > cls._IDLE_TIMEOUT
            ]
            for k in expired:
                cls._instances.pop(k, None)
                cls._last_access.pop(k, None)
            if expired:
                logger.info("__new__: 清理 %d 个空闲实例", len(expired))

            # LRU 驱逐：超过容量时驱逐最久未访问的实例
            if len(cls._instances) >= cls._MAX_INSTANCES and cache_key not in cls._instances:
                lru_key = min(cls._last_access, key=cls._last_access.__getitem__)
                cls._instances.pop(lru_key, None)
                cls._last_access.pop(lru_key, None)
                logger.info(
                    "__new__: LRU 驱逐 key=%s (username=%s, connection_id=%s)",
                    lru_key, lru_key[0], lru_key[1],
                )

            if cache_key not in cls._instances:
                cls._instances[cache_key] = super().__new__(cls)
            cls._last_access[cache_key] = now
        return cls._instances[cache_key]

    def __init__(self, connection_id: int, username: str = ""):
        cache_key = (username, connection_id)
        if (
            getattr(self, "_initialized", False)
            and getattr(self, "_cache_key", None) == cache_key
        ):
            return
        self._initialized = True
        self._cache_key = cache_key
        self._connection_id = connection_id
        self._username = username
        self._session = _get_http_session()
        self._ds_connection_cache: Dict[str, "TableauConnection|_CachedTableauConnection"] = {}
        self._MAX_CACHE_SIZE = 500

    def _get_connection_by_luid(
        self, datasource_luid: str, connection_id: int,
    ) -> "TableauConnection|_CachedTableauConnection":
        """通过 datasource_luid 查找对应的 TableauConnection（带内存缓存）。"""
        cache_key = f"{connection_id}:{datasource_luid}"
        if cache_key in self._ds_connection_cache:
            return self._ds_connection_cache[cache_key]

        from app.core.database import SessionLocal
        session = SessionLocal()
        conn = None
        try:
            asset = session.query(TableauAsset).filter(
                TableauAsset.tableau_id == datasource_luid,
                TableauAsset.connection_id == connection_id,
                TableauAsset.is_deleted == False,
            ).first()

            if not asset:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="数据源不存在或已删除或不属于该连接",
                    details={"datasource_luid": datasource_luid, "connection_id": connection_id},
                )

            conn = session.query(TableauConnection).filter(
                TableauConnection.id == connection_id,
            ).first()

            if not conn:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="数据源关联的连接不存在",
                    details={"datasource_luid": datasource_luid, "connection_id": connection_id},
                )

            conn_attrs = {
                "id": conn.id,
                "server_url": conn.server_url,
                "site": conn.site,
                "token_name": conn.token_name,
                "token_encrypted": conn.token_encrypted,
                "is_active": conn.is_active,
                "last_test_success": conn.last_test_success,
                "mcp_direct_enabled": getattr(conn, "mcp_direct_enabled", False),
                "mcp_server_url": getattr(conn, "mcp_server_url", None),
            }
            conn_attrs.update(_load_active_tableau_mcp_binding(conn.id) or {})
        finally:
            session.close()

        if len(self._ds_connection_cache) >= self._MAX_CACHE_SIZE:
            keys_to_remove = list(self._ds_connection_cache.keys())[: len(self._ds_connection_cache) // 2]
            for k in keys_to_remove:
                del self._ds_connection_cache[k]
            logger.warning("连接缓存超限，已清理 %d 条旧缓存", len(keys_to_remove))

        cached_conn = _CachedTableauConnection(**conn_attrs)
        self._ds_connection_cache[cache_key] = cached_conn
        return cached_conn

    def _get_connection_by_id(self, connection_id: int) -> "_CachedTableauConnection":
        """Load a TableauConnection by id for generic MCP host operations."""
        cache_key = f"{connection_id}:__connection__"
        cached = self._ds_connection_cache.get(cache_key)
        if isinstance(cached, _CachedTableauConnection):
            return cached

        from services.tableau.models import TableauConnection as _TableauConnection

        db = TableauDatabase()
        session = db.session
        try:
            conn = session.query(_TableauConnection).filter(
                _TableauConnection.id == connection_id,
            ).first()

            if not conn:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="Tableau 连接不存在",
                    details={"connection_id": connection_id},
                )

            conn_attrs = {
                "id": conn.id,
                "server_url": conn.server_url,
                "site": conn.site,
                "token_name": conn.token_name,
                "token_encrypted": conn.token_encrypted,
                "is_active": conn.is_active,
                "last_test_success": conn.last_test_success,
                "mcp_direct_enabled": getattr(conn, "mcp_direct_enabled", False),
                "mcp_server_url": getattr(conn, "mcp_server_url", None),
            }
            conn_attrs.update(_load_active_tableau_mcp_binding(conn.id) or {})
        finally:
            session.close()

        if len(self._ds_connection_cache) >= self._MAX_CACHE_SIZE:
            keys_to_remove = list(self._ds_connection_cache.keys())[: len(self._ds_connection_cache) // 2]
            for key in keys_to_remove:
                del self._ds_connection_cache[key]
            logger.warning("连接缓存超限，已清理 %d 条旧缓存", len(keys_to_remove))

        cached_conn = _CachedTableauConnection(**conn_attrs)
        self._ds_connection_cache[cache_key] = cached_conn
        return cached_conn

    def _resolve_mcp_connection_id(self, connection_id: Optional[int]) -> int:
        resolved = connection_id if connection_id is not None else self._connection_id
        if resolved is None:
            raise TableauMCPError(
                code="NLQ_009",
                message="connection_id 为必填参数（MCP 查询禁止空上下文）",
                details={},
            )
        return resolved

    def _get_connection_for_mcp_context(
        self,
        *,
        connection_id: int,
        datasource_luid: Optional[str] = None,
    ) -> "TableauConnection|_CachedTableauConnection":
        if datasource_luid:
            return self._get_connection_by_luid(datasource_luid, connection_id)
        return self._get_connection_by_id(connection_id)

    def _validate_mcp_context_connection(
        self,
        conn: "TableauConnection|_CachedTableauConnection",
        *,
        connection_id: int,
        datasource_luid: Optional[str] = None,
    ) -> None:
        details: Dict[str, Any] = {"connection_id": connection_id}
        if datasource_luid:
            details["datasource_luid"] = datasource_luid

        if not conn.is_active:
            raise TableauMCPError(
                code="NLQ_009",
                message="Tableau 连接已禁用",
                details=details,
            )
        if conn.last_test_success is False:
            raise TableauMCPError(
                code="NLQ_009",
                message="Tableau 连接测试失败，请联系管理员",
                details=details,
            )
        if not getattr(conn, "mcp_direct_enabled", False):
            raise TableauMCPError(
                code="MCP_010",
                message="连接未开启 V2 直连模式，请使用 V1 API",
                details={"connection_id": connection_id},
            )

    def _runtime_context(
        self,
        conn: "TableauConnection|_CachedTableauConnection",
        *,
        connection_id: int,
        user_id: Optional[int] = None,
        trace_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        conn_mcp_server_id = getattr(conn, "mcp_server_id", None)
        raw_mcp_url = getattr(conn, "mcp_server_url", None)
        should_lookup_binding = isinstance(conn_mcp_server_id, int) or isinstance(raw_mcp_url, str)
        binding = _load_active_tableau_mcp_binding(connection_id) if should_lookup_binding else None
        binding = binding or {}
        return {
            "tableau_connection_id": connection_id,
            "mcp_server_id": binding.get("mcp_server_id") or (conn_mcp_server_id if isinstance(conn_mcp_server_id, int) else None),
            "user_id": user_id if user_id is not None else _user_id_var.get(),
            "trace_id": trace_id or _trace_id_var.get() or str(uuid.uuid4()),
        }

    # ─────────────────────────────────────────────────────────────────────────
    # 公开 API
    # ─────────────────────────────────────────────────────────────────────────

    def query_datasource(
        self,
        datasource_luid: str,
        query: Dict[str, Any],
        limit: int = 1000,
        timeout: int = 30,
        connection_id: int = None,
        jwt_token: Optional[str] = None,
        user_id: Optional[int] = None,
        trace_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        通过 Tableau MCP 查询数据源（标准 MCP tools/call）。

        参数：
            datasource_luid: Tableau 数据源 LUID
            query: VizQL 查询 JSON（符合 PRD §5.5.2 格式）
            limit: 最大返回行数（默认 1000）
            timeout: 超时秒数（默认 30）
            connection_id: 租户连接 ID（必填，约束 D）
            jwt_token: Tableau Connected Apps JWT（非 None 时以用户身份发请求，
                       注入 Authorization: Bearer header，替代全局 PAT）

        返回：
            {"fields": [...], "rows": [[...], ...]}（符合 PRD §5.5.3 格式）

        异常：
            TableauMCPError: NLQ_006 / NLQ_007 / NLQ_009 / MCP_010

        T-R1 变更：调用标准 MCP tools/call 接口，session 生命周期由模块级管理。
        PAT 不再通过 env 注入（由 MCP server 进程持有）。
        """
        if connection_id is None:
            raise TableauMCPError(
                code="NLQ_009",
                message="connection_id 为必填参数（MCP 查询禁止空上下文）",
                details={"datasource_luid": datasource_luid},
            )

        token = _connection_id_var.set(connection_id)
        try:
            conn = self._get_connection_by_luid(datasource_luid, connection_id)

            # 校验连接可用性
            if not conn.is_active:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="Tableau 连接已禁用",
                    details={"datasource_luid": datasource_luid},
                )
            if conn.last_test_success is False:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="Tableau 连接测试失败，请联系管理员",
                    details={"datasource_luid": datasource_luid},
                )

            # 校验 V2 直连开关
            if not getattr(conn, "mcp_direct_enabled", False):
                raise TableauMCPError(
                    code="MCP_010",
                    message="连接未开启 V2 直连模式，请使用 V1 API",
                    details={"connection_id": connection_id},
                )

            # 多站点 session 路由（P0 改造）
            site_key = _get_site_key(conn)
            session_state = _get_or_create_session_state(site_key)
            # base_url：优先 conn.mcp_server_url，fallback 到全局配置
            effective_base_url = _get_effective_mcp_base_url(conn)
            mcp_context = self._runtime_context(
                conn,
                connection_id=connection_id,
                user_id=user_id,
                trace_id=trace_id,
            )

            # 组装 MCP tools/call 请求（limit 在 arguments 顶层，verified by tools/list）
            payload = self._build_jsonrpc_request(
                datasource_luid=datasource_luid,
                query=query,
                limit=limit,
            )

            return self._query_datasource_with_retry(
                payload=payload,
                timeout=timeout,
                site_key=site_key,
                session_state=session_state,
                base_url=effective_base_url,
                jwt_token=jwt_token,
                datasource_luid=datasource_luid,
                mcp_context=mcp_context,
            )
        finally:
            _connection_id_var.reset(token)

    def list_tools(
        self,
        timeout: int = 30,
        connection_id: Optional[int] = None,
        datasource_luid: Optional[str] = None,
        jwt_token: Optional[str] = None,
        user_id: Optional[int] = None,
        trace_id: Optional[str] = None,
    ) -> list[Dict[str, Any]]:
        """Public MCP tools/list API for host runtimes."""
        resolved_connection_id = self._resolve_mcp_connection_id(connection_id)
        token = _connection_id_var.set(resolved_connection_id)
        try:
            conn = self._get_connection_for_mcp_context(
                connection_id=resolved_connection_id,
                datasource_luid=datasource_luid,
            )
            self._validate_mcp_context_connection(
                conn,
                connection_id=resolved_connection_id,
                datasource_luid=datasource_luid,
            )
            site_key = _get_site_key(conn)
            session_state = _get_or_create_session_state(site_key)
            effective_base_url = _get_effective_mcp_base_url(conn)
            mcp_context = self._runtime_context(
                conn,
                connection_id=resolved_connection_id,
                user_id=user_id,
                trace_id=trace_id,
            )
            return self._list_mcp_tools(
                timeout=timeout,
                site_key=site_key,
                session_state=session_state,
                base_url=effective_base_url,
                jwt_token=jwt_token,
                mcp_context=mcp_context,
            )
        finally:
            _connection_id_var.reset(token)

    def call_tool(
        self,
        tool_name: str,
        arguments: Optional[Dict[str, Any]] = None,
        timeout: int = 30,
        connection_id: Optional[int] = None,
        datasource_luid: Optional[str] = None,
        jwt_token: Optional[str] = None,
        user_id: Optional[int] = None,
        trace_id: Optional[str] = None,
    ) -> Any:
        """Public generic MCP tools/call API for host runtimes."""
        name = str(tool_name or "").strip()
        if not name:
            raise TableauMCPError(
                code="NLQ_006",
                message="MCP tool name 不能为空",
                details={},
            )
        if arguments is None:
            call_arguments: Dict[str, Any] = {}
        elif isinstance(arguments, dict):
            call_arguments = arguments
        else:
            raise TableauMCPError(
                code="NLQ_006",
                message="MCP tool arguments 必须是对象",
                details={"argument_type": type(arguments).__name__},
            )

        resolved_connection_id = self._resolve_mcp_connection_id(connection_id)
        token = _connection_id_var.set(resolved_connection_id)
        try:
            conn = self._get_connection_for_mcp_context(
                connection_id=resolved_connection_id,
                datasource_luid=datasource_luid,
            )
            self._validate_mcp_context_connection(
                conn,
                connection_id=resolved_connection_id,
                datasource_luid=datasource_luid,
            )
            site_key = _get_site_key(conn)
            session_state = _get_or_create_session_state(site_key)
            effective_base_url = _get_effective_mcp_base_url(conn)
            mcp_context = self._runtime_context(
                conn,
                connection_id=resolved_connection_id,
                user_id=user_id,
                trace_id=trace_id,
            )
            payload = {
                "jsonrpc": "2.0",
                "id": _next_id(),
                "method": "tools/call",
                "params": {
                    "name": name,
                    "arguments": call_arguments,
                },
            }
            response = self._send_jsonrpc(
                payload,
                timeout=timeout,
                site_key=site_key,
                session_state=session_state,
                base_url=effective_base_url,
                jwt_token=jwt_token,
                mcp_context=mcp_context,
            )
            return _parse_tool_json_text(response, tool_name=name)
        finally:
            _connection_id_var.reset(token)

    def query_datasource_natural_language(
        self,
        datasource_luid: str,
        question: str,
        limit: int = 1000,
        timeout: int = 30,
        connection_id: int = None,
        jwt_token: Optional[str] = None,
        allowed_tool_names: Optional[Iterable[str]] = None,
        user_id: Optional[int] = None,
        trace_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Invoke an explicitly allowlisted Tableau MCP natural-language query tool.

        This method intentionally does not construct fields, aggregations, filters,
        or any business query plan. It discovers MCP tools via tools/list, selects
        only an allowed NL tool name, and forwards the original question plus the
        selected datasource identifier.
        """
        if connection_id is None:
            raise TableauMCPError(
                code="NLQ_009",
                message="connection_id 为必填参数（MCP 查询禁止空上下文）",
                details={"datasource_luid": datasource_luid},
            )

        token = _connection_id_var.set(connection_id)
        try:
            conn = self._get_connection_by_luid(datasource_luid, connection_id)

            if not conn.is_active:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="Tableau 连接已禁用",
                    details={"datasource_luid": datasource_luid},
                )
            if conn.last_test_success is False:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="Tableau 连接测试失败，请联系管理员",
                    details={"datasource_luid": datasource_luid},
                )
            if not getattr(conn, "mcp_direct_enabled", False):
                raise TableauMCPError(
                    code="MCP_010",
                    message="连接未开启 V2 直连模式，请使用 V1 API",
                    details={"connection_id": connection_id},
                )

            site_key = _get_site_key(conn)
            session_state = _get_or_create_session_state(site_key)
            effective_base_url = _get_effective_mcp_base_url(conn)
            mcp_context = self._runtime_context(
                conn,
                connection_id=connection_id,
                user_id=user_id,
                trace_id=trace_id,
            )

            tools = self._list_mcp_tools(
                timeout=timeout,
                site_key=site_key,
                session_state=session_state,
                base_url=effective_base_url,
                jwt_token=jwt_token,
                mcp_context=mcp_context,
            )
            selected_tool = _select_nl_query_tool(
                tools,
                allowed_tool_names=allowed_tool_names,
            )
            if selected_tool is None:
                available_tool_names = [_mcp_tool_name(tool) for tool in tools]
                raise TableauMCPError(
                    code=MCP_NL_TOOL_UNAVAILABLE,
                    message="Tableau MCP 未暴露已配置的自然语言查询工具",
                    details={
                        "datasource_luid": datasource_luid,
                        "available_tools": available_tool_names,
                        "allowed_tools": list(_allowed_nl_query_tool_names(allowed_tool_names)),
                        "structured_query_datasource_available": (
                            "query-datasource" in available_tool_names
                        ),
                    },
                )

            tool_name = _mcp_tool_name(selected_tool)
            arguments = _build_nl_query_tool_arguments(
                tool=selected_tool,
                datasource_luid=datasource_luid,
                question=question,
                limit=limit,
            )
            payload = {
                "jsonrpc": "2.0",
                "id": _next_id(),
                "method": "tools/call",
                "params": {
                    "name": tool_name,
                    "arguments": arguments,
                },
            }

            response = self._send_jsonrpc(
                payload,
                timeout=timeout,
                site_key=site_key,
                session_state=session_state,
                base_url=effective_base_url,
                jwt_token=jwt_token,
                mcp_context=mcp_context,
            )
            data = _parse_tool_json_text(response, tool_name=tool_name)
            if isinstance(data, dict):
                return _normalize_query_datasource_result(data)
            return {"data": data}
        finally:
            _connection_id_var.reset(token)

    def _query_datasource_with_retry(
        self,
        *,
        payload: dict,
        timeout: int,
        site_key: Optional[str],
        session_state: "_MCPSessionState",
        base_url: str,
        jwt_token: Optional[str],
        datasource_luid: str,
        mcp_context: Optional[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Execute query-datasource with bounded retry for transient MCP failures."""
        budget = min(float(timeout), _QUERY_RETRY_BUDGET_SECONDS)
        deadline = time.monotonic() + max(1.0, budget)
        attempt = 0
        retry_errors: list[str] = []

        while True:
            attempt += 1
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise TableauMCPError(
                    code="NLQ_007",
                    message="MCP 查询超过重试总预算",
                    details={
                        "datasource_luid": datasource_luid,
                        "attempts": attempt - 1,
                        "budget_seconds": budget,
                        "retry_errors": retry_errors[-3:],
                    },
                )
            attempt_timeout = max(1, min(int(timeout), int(remaining)))
            try:
                response = self._send_jsonrpc(
                    payload,
                    timeout=attempt_timeout,
                    site_key=site_key,
                    session_state=session_state,
                    base_url=base_url,
                    jwt_token=jwt_token,
                    mcp_context=mcp_context,
                )
                return self._parse_jsonrpc_response(response)
            except TableauMCPError as exc:
                retry_kind = _retry_kind_for_mcp_error(exc)
                max_attempts = _max_attempts_for_retry_kind(retry_kind)
                if retry_kind is None or attempt >= max_attempts:
                    if retry_errors:
                        exc.details.setdefault("retry_attempts", attempt - 1)
                        exc.details.setdefault("retry_errors", retry_errors[-3:])
                    raise

                backoff = _RETRY_BACKOFF_SECONDS[min(attempt - 1, len(_RETRY_BACKOFF_SECONDS) - 1)]
                remaining_after_backoff = deadline - time.monotonic() - backoff
                if remaining_after_backoff < _MIN_RETRY_REMAINING_SECONDS:
                    exc.details.setdefault("retry_attempts", attempt - 1)
                    exc.details.setdefault("retry_budget_exhausted", True)
                    raise

                error_summary = _mcp_error_summary(exc)
                retry_errors.append(error_summary)
                logger.warning(
                    "Retrying Tableau MCP query-datasource after transient %s error "
                    "(attempt=%s/%s, datasource_luid=%s, remaining=%.2fs): %s",
                    retry_kind,
                    attempt + 1,
                    max_attempts,
                    datasource_luid,
                    max(0.0, deadline - time.monotonic()),
                    error_summary,
                )
                time.sleep(backoff)

    def _list_mcp_tools(
        self,
        *,
        timeout: int,
        site_key: Optional[str],
        session_state: "_MCPSessionState",
        base_url: Optional[str],
        jwt_token: Optional[str],
        mcp_context: Optional[Dict[str, Any]] = None,
    ) -> list[Dict[str, Any]]:
        """Discover MCP tools through tools/list for the prepared connection context."""
        payload = {
            "jsonrpc": "2.0",
            "id": _next_id(),
            "method": "tools/list",
            "params": {},
        }
        response = self._send_jsonrpc(
            payload,
            timeout=timeout,
            site_key=site_key,
            session_state=session_state,
            base_url=base_url,
            jwt_token=jwt_token,
            mcp_context=mcp_context,
        )
        return _parse_tools_list_response(response)

    def list_datasources(
        self,
        limit: int = 50,
        timeout: int = 30,
        connection_id: Optional[int] = None,
        jwt_token: Optional[str] = None,
        user_id: Optional[int] = None,
        trace_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        通过 Tableau MCP 列出可用的数据源（用于动态数据源发现）。

        当本地 TableauAsset 表为空时，NLQ 路由层调用此方法通过 MCP 动态发现数据源。

        参数：
            limit: 最大返回条数（默认 50）
            timeout: 超时秒数（默认 30）
            connection_id: 指定 Tableau 连接 ID（None 时取第一条活跃连接，向后兼容）
            jwt_token: Tableau Connected Apps JWT（非 None 时以用户身份发请求，替代全局 PAT）

        返回：
            {"datasources": [{"luid": "...", "name": "..."}, ...]}
        """
        from services.tableau.models import TableauConnection as _TableauConnection

        db = TableauDatabase()
        session = db.session
        try:
            query_filter = session.query(_TableauConnection).filter(
                _TableauConnection.is_active == True,
            )
            if connection_id is not None:
                query_filter = query_filter.filter(_TableauConnection.id == connection_id)
            conn_record = query_filter.order_by(_TableauConnection.id.asc()).first()

            if not conn_record:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="无活跃的 Tableau 连接",
                    details={"connection_id": connection_id},
                )
        finally:
            session.close()

        token = _connection_id_var.set(conn_record.id)
        try:
            site_key = _get_site_key(conn_record)
            session_state = _get_or_create_session_state(site_key)
            effective_base_url = _get_effective_mcp_base_url(conn_record)
            mcp_context = self._runtime_context(
                conn_record,
                connection_id=conn_record.id,
                user_id=user_id,
                trace_id=trace_id,
            )

            # 官方 Tableau MCP 工具名使用连字符。
            payload = {
                "jsonrpc": "2.0",
                "id": _next_id(),
                "method": "tools/call",
                "params": {
                    "name": "list-datasources",
                    "arguments": {"limit": limit},
                },
            }

            response = self._send_jsonrpc(
                payload,
                timeout=timeout,
                site_key=site_key,
                session_state=session_state,
                base_url=effective_base_url,
                jwt_token=jwt_token,
                mcp_context=mcp_context,
            )

            data = _parse_tool_json_text(response, tool_name="list-datasources")
            if isinstance(data, dict) and isinstance(data.get("datasources"), list):
                return data
            if isinstance(data, list):
                return {"datasources": data}
            return {"datasources": [], "raw": data}
        finally:
            _connection_id_var.reset(token)

    def get_datasource_metadata(
        self,
        datasource_luid: str,
        timeout: int = 30,
        user_id: Optional[int] = None,
        trace_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        通过 Tableau MCP 获取数据源的字段元数据（用于 NLQ 动态数据源发现）。

        当本地 TableauAsset 表无数据时，NLQ 路由层先调用 list_datasources 发现数据源，
        再调用此方法获取字段信息，构建 LLM prompt。

        返回：
            {"fields": [{"name": "...", "dataType": "...", "role": "..."}, ...]}
        """
        from services.tableau.models import TableauConnection as _TableauConnection

        db = TableauDatabase()
        session = db.session
        try:
            conn_record = session.query(_TableauConnection).filter(
                _TableauConnection.is_active == True,
                _TableauConnection.id == self._connection_id,
            ).order_by(_TableauConnection.id.asc()).first()

            if not conn_record:
                raise TableauMCPError(
                    code="NLQ_009",
                    message="无活跃的 Tableau 连接",
                    details={"connection_id": self._connection_id},
                )
        finally:
            session.close()

        token = _connection_id_var.set(conn_record.id)
        try:
            site_key = _get_site_key(conn_record)
            session_state = _get_or_create_session_state(site_key)
            effective_base_url = _get_effective_mcp_base_url(conn_record)
            mcp_context = self._runtime_context(
                conn_record,
                connection_id=conn_record.id,
                user_id=user_id,
                trace_id=trace_id,
            )

            # 调用 get-datasource-metadata 工具
            payload = {
                "jsonrpc": "2.0",
                "id": _next_id(),
                "method": "tools/call",
                "params": {
                    "name": "get-datasource-metadata",
                    "arguments": {"datasourceLuid": datasource_luid},
                },
            }

            response = self._send_jsonrpc(
                payload,
                timeout=timeout,
                site_key=site_key,
                session_state=session_state,
                base_url=effective_base_url,
                mcp_context=mcp_context,
            )

            parsed = self._parse_jsonrpc_response(response)
            content = parsed.get("content", [])
            text = _extract_text(content)
            if text:
                try:
                    data = json.loads(text)
                    fields = extract_datasource_metadata_fields(data)
                    if fields and isinstance(data, dict):
                        return {**data, "fields": fields}
                    return data
                except json.JSONDecodeError:
                    pass
            fields = extract_datasource_metadata_fields(parsed)
            return {"fields": fields, "raw": parsed}
        finally:
            _connection_id_var.reset(token)

    # ─────────────────────────────────────────────────────────────────────────
    # 内部方法
    # ─────────────────────────────────────────────────────────────────────────

    def _decrypt_pat(self, conn) -> str:
        """解密 PAT Secret（为多租户预留，本次 MVP 不调用）。"""
        try:
            crypto = get_tableau_crypto()
            return crypto.decrypt(conn.token_encrypted)
        except Exception as e:
            logger.error("PAT 解密失败: %s", e)
            raise TableauMCPError(
                code="NLQ_009",
                message="认证凭据解密失败",
                details={"connection_id": conn.id},
            )

    def _build_jsonrpc_request(
        self,
        datasource_luid: str,
        query: Dict[str, Any],
        limit: int,
    ) -> dict:
        """
        组装 MCP tools/call JSON-RPC 请求。

        T-R1：使用标准 MCP method "tools/call"，
        替代旧版自定义 REST "query-datasource"。
        注意：PAT 不再通过 env 字段注入，由 MCP server 进程 env 持有。
        """
        return {
            "jsonrpc": "2.0",
            "id": _next_id(),
            "method": "tools/call",
            "params": {
                "name": "query-datasource",
                "arguments": {
                    "datasourceLuid": datasource_luid,
                    "query": query,
                    "limit": limit,
                },
            },
        }

    def _send_jsonrpc(
        self,
        payload: dict,
        timeout: int,
        site_key: Optional[str] = None,
        session_state: Optional[_MCPSessionState] = None,
        base_url: Optional[str] = None,
        jwt_token: Optional[str] = None,
        mcp_context: Optional[Dict[str, Any]] = None,
    ) -> dict:
        """
        发送 MCP JSON-RPC 请求（内部处理 session 生命周期）。

        参数：
            payload: JSON-RPC 请求体
            timeout: 超时秒数
            site_key: 站点唯一键（多站点改造，P0 新增）
            session_state: 指定 session 状态实例（默认使用全局 _mcp_session_state）
            base_url: MCP Server URL（优先用参数值，fallback 到全局配置）
            jwt_token: Tableau Connected Apps JWT（非 None 时以用户身份发请求，替代全局 PAT）

        重试策略：
            - 网络错误 / 5xx：重试 1 次，间隔 1s
            - 4xx：不重试
            - session 过期：自动重建 session + 重试 1 次（不计入外层重试）
        """
        state = session_state if session_state is not None else _mcp_session_state
        method = payload.get("method", "unknown")

        for attempt in range(2):
            try:
                # 确保 session 已建立（懒加载）
                _ensure_session(
                    timeout=timeout,
                    site_key=site_key,
                    base_url=base_url,
                    session_state=state,
                    jwt_token=jwt_token,
                    mcp_context=mcp_context,
                )

                # 更新最后活跃时间（每次成功建立 session 后）
                with state.lock:
                    state.last_activity = time.monotonic()

                return _post_mcp(
                    payload,
                    method=method,
                    timeout=timeout,
                    expect_sse=True,
                    session_state=state,
                    base_url=base_url,
                    jwt_token=jwt_token,
                    mcp_context=mcp_context,
                )

            except _SessionExpiredError:
                # Session 过期：清空并重建，不计入外层重试
                logger.warning("MCP session 过期，尝试重建: %s", method)
                state.reset()
                _ensure_session(
                    timeout=timeout,
                    site_key=site_key,
                    base_url=base_url,
                    session_state=state,
                    jwt_token=jwt_token,
                    mcp_context=mcp_context,
                )
                with state.lock:
                    state.last_activity = time.monotonic()
                # 重试 1 次（这次用新 session）
                return _post_mcp(
                    payload,
                    method=method,
                    timeout=timeout,
                    expect_sse=True,
                    session_state=state,
                    base_url=base_url,
                    jwt_token=jwt_token,
                    mcp_context=mcp_context,
                )

            except TableauMCPError:
                raise  # 已构造好，直接透传

    def _parse_jsonrpc_response(self, body: dict) -> dict:
        """
        解析 MCP tools/call JSON-RPC 响应。

        MCP 协议下 query-datasource 的响应结构：
            {
              "jsonrpc": "2.0",
              "id": N,
              "result": {
                "content": [{"type": "text", "text": "{\"fields\":[...],\"rows\":[[...]]}"}],
                "isError": false
              }
            }

        映射到 PRD §5.5.3 契约：
            - content[0].text 是 Tableau 返回的 JSON 字符串（fields + rows）
            - 解析该 JSON 返回 {"fields": [...], "rows": [[...], ...]}
        """
        if "error" in body:
            err = body["error"]
            message = err.get("message", "MCP 返回错误")
            raise TableauMCPError(
                code=_map_mcp_error(err.get("code"), message=message),
                message=message,
                details=err.get("data", {}),
            )

        result = body.get("result", {})

        # tools/call 的工具级错误走 isError + content
        if result.get("isError"):
            error_text = _extract_text(result.get("content", []))
            raise TableauMCPError(
                code="NLQ_006",
                message=f"MCP 工具执行失败: {error_text[:200]}",
                details={"tool": "query-datasource", "raw": error_text[:500]},
            )

        content = result.get("content", [])
        text_payload = _extract_text(content)

        try:
            data = json.loads(text_payload)
        except json.JSONDecodeError as e:
            raise TableauMCPError(
                code="NLQ_006",
                message="query-datasource 返回非 JSON 文本",
                details={"raw": text_payload[:500], "json_error": str(e)},
            )

        if not isinstance(data, dict):
            raise TableauMCPError(
                code="NLQ_006",
                message="query-datasource 返回值不是对象",
                details={"type": type(data).__name__},
            )
        return _normalize_query_datasource_result(data)


# ─────────────────────────────────────────────────────────────────────────────
# 辅助函数
# ─────────────────────────────────────────────────────────────────────────────

def _extract_text(content: list) -> str:
    """从 MCP content[] 数组中提取 text 类型的值（拼接，兼容多段）。"""
    parts = [c.get("text", "") for c in content if c.get("type") == "text"]
    return "".join(parts)


def _parse_tool_json_text(body: dict, tool_name: str) -> Any:
    """Parse a generic MCP tools/call JSON text payload."""
    if "error" in body:
        err = body["error"]
        message = err.get("message", "MCP 返回错误")
        raise TableauMCPError(
            code=_map_mcp_error(err.get("code"), message=message),
            message=message,
            details=err.get("data", {}),
        )

    result = body.get("result", {})
    if result.get("isError"):
        error_text = _extract_text(result.get("content", []))
        raise TableauMCPError(
            code="NLQ_006",
            message=f"MCP 工具执行失败: {error_text[:200]}",
            details={"tool": tool_name, "raw": error_text[:500]},
        )

    text_payload = _extract_text(result.get("content", []))
    try:
        return json.loads(text_payload)
    except json.JSONDecodeError as e:
        raise TableauMCPError(
            code="NLQ_006",
            message=f"{tool_name} 返回非 JSON 文本",
            details={"raw": text_payload[:500], "json_error": str(e)},
        )


def _parse_tools_list_response(body: dict) -> list[Dict[str, Any]]:
    """Parse standard MCP tools/list response without inferring tool semantics."""
    if "error" in body:
        err = body["error"]
        message = err.get("message", "MCP 返回错误")
        raise TableauMCPError(
            code=_map_mcp_error(err.get("code"), message=message),
            message=message,
            details=err.get("data", {}),
        )

    result = body.get("result", body)
    tools = result.get("tools") if isinstance(result, dict) else None
    if not isinstance(tools, list):
        raise TableauMCPError(
            code="NLQ_006",
            message="MCP tools/list 返回值缺少 tools 数组",
            details={"raw": body},
        )

    normalized_tools: list[Dict[str, Any]] = []
    for tool in tools:
        if isinstance(tool, dict):
            name = str(tool.get("name") or "").strip()
            if name:
                normalized_tools.append(tool)
        elif isinstance(tool, str):
            name = tool.strip()
            if name:
                normalized_tools.append({"name": name})
    return normalized_tools


def _mcp_tool_name(tool: Any) -> str:
    if isinstance(tool, dict):
        return str(tool.get("name") or "").strip()
    return str(tool or "").strip()


def _allowed_nl_query_tool_names(
    allowed_tool_names: Optional[Iterable[str]] = None,
) -> tuple[str, ...]:
    if isinstance(allowed_tool_names, str):
        raw_names = (allowed_tool_names,)
    else:
        raw_names = (
            allowed_tool_names
            if allowed_tool_names is not None
            else _DEFAULT_NL_QUERY_TOOL_NAMES
        )
    names: list[str] = []
    seen: set[str] = set()
    for raw_name in raw_names:
        name = str(raw_name or "").strip()
        if not name or name in seen:
            continue
        names.append(name)
        seen.add(name)
    return tuple(names)


def _select_nl_query_tool(
    tools: list[Dict[str, Any]],
    *,
    allowed_tool_names: Optional[Iterable[str]] = None,
) -> Optional[Dict[str, Any]]:
    """Select an exact allowlisted NL tool name; never select structured query-datasource."""
    tools_by_name = {_mcp_tool_name(tool): tool for tool in tools}
    for tool_name in _allowed_nl_query_tool_names(allowed_tool_names):
        if tool_name in _STRUCTURED_QUERY_DATASOURCE_TOOL_NAMES:
            continue
        tool = tools_by_name.get(tool_name)
        if tool is not None:
            return tool
    return None


def _build_nl_query_tool_arguments(
    *,
    tool: Dict[str, Any],
    datasource_luid: str,
    question: str,
    limit: int,
) -> Dict[str, Any]:
    """Build only passthrough NL arguments from the tool schema when available."""
    properties = _tool_schema_properties(tool)
    question_key = _pick_schema_property(properties, _NL_QUESTION_ARGUMENT_NAMES)
    datasource_key = _pick_schema_property(properties, _NL_DATASOURCE_ARGUMENT_NAMES)
    if properties and (question_key is None or datasource_key is None):
        raise TableauMCPError(
            code=MCP_NL_TOOL_UNAVAILABLE,
            message="已配置的 MCP 自然语言查询工具缺少问题或数据源入参",
            details={
                "tool": _mcp_tool_name(tool),
                "schema_properties": sorted(properties.keys()),
            },
        )

    arguments = {
        question_key or _NL_QUESTION_ARGUMENT_NAMES[0]: question,
        datasource_key or _NL_DATASOURCE_ARGUMENT_NAMES[0]: datasource_luid,
    }

    limit_key = _pick_schema_property(properties, _NL_LIMIT_ARGUMENT_NAMES)
    if limit_key is not None:
        arguments[limit_key] = limit
    return arguments


def _tool_schema_properties(tool: Dict[str, Any]) -> Dict[str, Any]:
    schema = tool.get("inputSchema") or tool.get("input_schema") or {}
    if not isinstance(schema, dict):
        return {}
    properties = schema.get("properties") or {}
    return properties if isinstance(properties, dict) else {}


def _pick_schema_property(
    properties: Dict[str, Any],
    candidates: tuple[str, ...],
) -> Optional[str]:
    if not properties:
        return None
    for candidate in candidates:
        if candidate in properties:
            return candidate
    properties_by_lower = {key.lower(): key for key in properties}
    for candidate in candidates:
        matched = properties_by_lower.get(candidate.lower())
        if matched:
            return matched
    return None


def _normalize_query_datasource_result(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Normalize official Tableau MCP query-datasource results.

    Current @tableau/mcp-server returns {"data": [{"field": value, ...}]} while
    older Mulan code expects {"fields": [...], "rows": [[...]]}. Preserve the
    original data array and add the tabular shape for downstream renderers.
    """
    if "rows" in data or "fields" in data:
        return data

    records = data.get("data")
    if not isinstance(records, list):
        return data

    if not records:
        return {**data, "fields": [], "rows": []}

    if not all(isinstance(record, dict) for record in records):
        return data

    fields = list(records[0].keys())
    rows = [[record.get(field) for field in fields] for record in records]
    return {**data, "fields": fields, "rows": rows}


def _map_mcp_error(code: Any, message: str = "") -> str:
    """
    将 MCP 错误码映射为 NLQ 系列错误码。

    规则：
        - Tableau/LLM 相关错误 → NLQ_006
        - 超时 → NLQ_007
        - 权限/不存在 → NLQ_009
        - 其他 → NLQ_006
    """
    message_lower = message.lower()
    if "timeout" in message_lower or "timed out" in message_lower or "超时" in message:
        return "NLQ_007"
    if code is None:
        return "NLQ_006"
    code_str = str(code)
    # 常见 VizQL 错误码
    if code_str in ("forbidden", "unauthorized") or code == 403:
        return "NLQ_009"
    if code_str in ("not_found", "notexists") or code == 404:
        return "NLQ_009"
    # Tableau VizQL 特定错误
    if code_str.startswith("VIZQL_") or code_str.startswith("VIZQL-"):
        return "NLQ_006"
    return "NLQ_006"


def _retry_kind_for_mcp_error(exc: TableauMCPError) -> Optional[str]:
    """Classify retryable MCP failures without retrying business/schema errors."""
    text = _mcp_error_summary(exc).lower()
    if any(
        marker in text
        for marker in (
            "invalid arguments",
            "invalid_argument",
            "input validation error",
            "unauthorized",
            "forbidden",
            "permission",
            "权限",
            "认证",
            "字段不存在",
            "unknown field",
        )
    ):
        return None

    detail_kind = str((exc.details or {}).get("retry_kind") or "").strip().lower()
    if detail_kind in {"transport", "read_timeout"}:
        return detail_kind

    if any(
        marker in text
        for marker in (
            "econnreset",
            "econnrefused",
            "connection reset",
            "connection refused",
            "socket hang up",
            "remote end closed",
            "temporarily unavailable",
            "service unavailable",
        )
    ):
        return "transport"

    if exc.code == "NLQ_007" or any(marker in text for marker in ("read timeout", "read timed out", "查询超时")):
        return "read_timeout"

    return None


def _max_attempts_for_retry_kind(retry_kind: Optional[str]) -> int:
    if retry_kind == "transport":
        return _TRANSPORT_RETRY_MAX_ATTEMPTS
    if retry_kind == "read_timeout":
        return _READ_TIMEOUT_RETRY_MAX_ATTEMPTS
    return 1


def _mcp_error_summary(exc: TableauMCPError) -> str:
    details = exc.details or {}
    raw = details.get("raw") or details.get("error") or ""
    return f"{exc.code} {exc.message} {raw}"[:500]


# ─────────────────────────────────────────────────────────────────────────────
# 模块级 per-connection_id 访问器（约束 D）
# ─────────────────────────────────────────────────────────────────────────────

def get_tableau_mcp_client(
    connection_id: int,
    username: str = "",
) -> TableauMCPClient:
    """
    获取指定 (username, connection_id) 的 TableauMCPClient 实例（T-R1 per-user session）。

    每个 (username, connection_id) 组合对应唯一 client 实例，禁止跨用户共享。
    LRU 容量 50，符合 Spec 14 §V2 规范。

    参数：
        connection_id: Tableau 连接 ID（租户隔离）
        username: 当前用户名（用户隔离，空字符串表示匿名/系统调用）
    """
    return TableauMCPClient(connection_id=connection_id, username=username)
