"""add rule_configs and operator_id

Revision ID: 07c4d16b8335
Revises: 
Create Date: 2026-04-03 07:39:12.881260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07c4d16b8335'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_llm_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), server_default=sa.text("'openai'"), nullable=True),
    sa.Column('base_url', sa.String(length=512), server_default=sa.text("'https://api.openai.com/v1'"), nullable=True),
    sa.Column('api_key_encrypted', sa.String(length=512), nullable=False),
    sa.Column('model', sa.String(length=128), server_default=sa.text("'gpt-4o-mini'"), nullable=True),
    sa.Column('temperature', sa.Float(), server_default=sa.text('CAST(0.7 AS FLOAT)'), nullable=True),
    sa.Column('max_tokens', sa.Integer(), server_default=sa.text('CAST(1024 AS INTEGER)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_groups_name'), 'auth_user_groups', ['name'], unique=True)
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'user'"), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('bi_data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('db_type', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_encrypted', sa.String(length=512), nullable=False),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bi_health_scan_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.Column('datasource_name', sa.String(length=128), nullable=False),
    sa.Column('db_type', sa.String(length=32), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_tables', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('total_issues', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('high_count', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('medium_count', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('low_count', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_health_scan_records_datasource_id'), 'bi_health_scan_records', ['datasource_id'], unique=False)
    op.create_table('bi_operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operator', sa.String(length=128), server_default=sa.text("'anonymous'"), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'success'"), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bi_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('requirement_type', sa.String(length=64), nullable=False),
    sa.Column('what_to_do', sa.Text(), nullable=False),
    sa.Column('why_to_do', sa.Text(), nullable=True),
    sa.Column('impact_scope', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('priority', sa.String(length=32), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('related_tables', sa.Text(), nullable=True),
    sa.Column('applicant', sa.String(length=128), nullable=True),
    sa.Column('assignee', sa.String(length=128), nullable=True),
    sa.Column('approver', sa.String(length=128), nullable=True),
    sa.Column('approve_comment', sa.Text(), nullable=True),
    sa.Column('approve_time', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bi_rule_change_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operator', sa.String(length=128), server_default=sa.text("'system'"), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('rule_section', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bi_rule_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('db_type', sa.String(length=32), nullable=False),
    sa.Column('suggestion', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_rule_configs_rule_id'), 'bi_rule_configs', ['rule_id'], unique=True)
    op.create_table('bi_scan_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=False),
    sa.Column('db_type', sa.String(length=32), nullable=False),
    sa.Column('table_count', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('total_violations', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('warning_count', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('info_count', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('duration_seconds', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'completed'"), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tableau_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('server_url', sa.String(length=512), nullable=False),
    sa.Column('site', sa.String(length=128), nullable=False),
    sa.Column('api_version', sa.String(length=16), server_default=sa.text("'3.21'"), nullable=True),
    sa.Column('connection_type', sa.String(length=16), server_default=sa.text("'mcp'"), nullable=False),
    sa.Column('token_name', sa.String(length=256), nullable=False),
    sa.Column('token_encrypted', sa.String(length=512), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('sync_interval_hours', sa.Integer(), server_default=sa.text('CAST(24 AS INTEGER)'), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_success', sa.Boolean(), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_duration_sec', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default=sa.text("'idle'"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tableau_datasource_semantics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('tableau_datasource_id', sa.String(length=256), nullable=False),
    sa.Column('semantic_name', sa.String(length=256), nullable=True),
    sa.Column('semantic_name_zh', sa.String(length=256), nullable=True),
    sa.Column('semantic_description', sa.Text(), nullable=True),
    sa.Column('business_definition', sa.Text(), nullable=True),
    sa.Column('usage_scenarios', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('steward', sa.String(length=128), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=16), server_default=sa.text("'low'"), nullable=True),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('source', sa.String(length=16), server_default=sa.text("'manual'"), nullable=True),
    sa.Column('current_version', sa.Integer(), server_default=sa.text('CAST(1 AS INTEGER)'), nullable=True),
    sa.Column('published_to_tableau', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'tableau_datasource_id', name='uq_ds_semantic_conn_ds')
    )
    op.create_index('ix_ds_semantic_conn_id', 'tableau_datasource_semantics', ['connection_id'], unique=False)
    op.create_index('ix_ds_semantic_status', 'tableau_datasource_semantics', ['status'], unique=False)
    op.create_table('tableau_field_semantics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_registry_id', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('tableau_field_id', sa.String(length=256), nullable=False),
    sa.Column('semantic_name', sa.String(length=256), nullable=True),
    sa.Column('semantic_name_zh', sa.String(length=256), nullable=True),
    sa.Column('semantic_definition', sa.Text(), nullable=True),
    sa.Column('metric_definition', sa.Text(), nullable=True),
    sa.Column('dimension_definition', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('enum_desc_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synonyms_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=16), server_default=sa.text("'low'"), nullable=True),
    sa.Column('is_core_field', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('source', sa.String(length=16), server_default=sa.text("'manual'"), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('CAST(1 AS INTEGER)'), nullable=True),
    sa.Column('published_to_tableau', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'tableau_field_id', name='uq_field_semantic_conn_fid')
    )
    op.create_index('ix_field_semantic_conn_id', 'tableau_field_semantics', ['connection_id'], unique=False)
    op.create_index('ix_field_semantic_reg_id', 'tableau_field_semantics', ['field_registry_id'], unique=False)
    op.create_index('ix_field_semantic_status', 'tableau_field_semantics', ['status'], unique=False)
    op.create_table('tableau_publish_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('tableau_object_id', sa.String(length=256), nullable=True),
    sa.Column('target_system', sa.String(length=32), server_default=sa.text("'tableau'"), nullable=True),
    sa.Column('publish_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diff_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('operator', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_publish_log_conn_status', 'tableau_publish_logs', ['connection_id', 'status'], unique=False)
    op.create_index('ix_publish_log_object', 'tableau_publish_logs', ['object_type', 'object_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_user_groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'permission_key')
    )
    op.create_table('auth_user_group_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_user_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('bi_health_scan_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('object_type', sa.String(length=16), nullable=False),
    sa.Column('object_name', sa.String(length=256), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['bi_health_scan_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issue_scan_severity', 'bi_health_scan_issues', ['scan_id', 'severity'], unique=False)
    op.create_table('tableau_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('tableau_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_name', sa.String(length=128), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('content_url', sa.String(length=512), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_generated_at', sa.DateTime(), nullable=True),
    sa.Column('ai_summary_error', sa.Text(), nullable=True),
    sa.Column('parent_workbook_id', sa.String(length=256), nullable=True),
    sa.Column('parent_workbook_name', sa.String(length=256), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sheet_type', sa.String(length=32), nullable=True),
    sa.Column('created_on_server', sa.DateTime(), nullable=True),
    sa.Column('updated_on_server', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('ai_explain', sa.Text(), nullable=True),
    sa.Column('ai_explain_at', sa.DateTime(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_count', sa.Integer(), nullable=True),
    sa.Column('is_certified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['tableau_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'tableau_id', name='uq_asset_conn_tid')
    )
    op.create_index('ix_asset_conn_deleted_type', 'tableau_assets', ['connection_id', 'is_deleted', 'asset_type'], unique=False)
    op.create_index('ix_asset_conn_parent', 'tableau_assets', ['connection_id', 'parent_workbook_id'], unique=False)
    op.create_table('tableau_datasource_semantic_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datasource_semantic_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_semantic_id'], ['tableau_datasource_semantics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ds_ver_sem_id', 'tableau_datasource_semantic_versions', ['datasource_semantic_id'], unique=False)
    op.create_table('tableau_field_semantic_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_semantic_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_semantic_id'], ['tableau_field_semantics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_field_ver_sem_id', 'tableau_field_semantic_versions', ['field_semantic_id'], unique=False)
    op.create_table('tableau_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'running'"), nullable=False),
    sa.Column('workbooks_synced', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('views_synced', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('dashboards_synced', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('datasources_synced', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('assets_deleted', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['tableau_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_synclog_conn_started', 'tableau_sync_logs', ['connection_id', 'started_at'], unique=False)
    op.create_table('tableau_asset_datasources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('datasource_name', sa.String(length=256), nullable=False),
    sa.Column('datasource_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['tableau_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'datasource_name', name='uq_asset_ds_name')
    )
    op.create_table('tableau_datasource_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('datasource_luid', sa.String(length=256), nullable=False),
    sa.Column('field_name', sa.String(length=256), nullable=False),
    sa.Column('field_caption', sa.String(length=256), nullable=True),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('aggregation', sa.String(length=32), nullable=True),
    sa.Column('is_calculated', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ai_caption', sa.String(length=256), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('ai_role', sa.String(length=32), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_annotated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['tableau_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dsfield_asset_luid', 'tableau_datasource_fields', ['asset_id', 'datasource_luid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dsfield_asset_luid', table_name='tableau_datasource_fields')
    op.drop_table('tableau_datasource_fields')
    op.drop_table('tableau_asset_datasources')
    op.drop_index('ix_synclog_conn_started', table_name='tableau_sync_logs')
    op.drop_table('tableau_sync_logs')
    op.drop_index('ix_field_ver_sem_id', table_name='tableau_field_semantic_versions')
    op.drop_table('tableau_field_semantic_versions')
    op.drop_index('ix_ds_ver_sem_id', table_name='tableau_datasource_semantic_versions')
    op.drop_table('tableau_datasource_semantic_versions')
    op.drop_index('ix_asset_conn_parent', table_name='tableau_assets')
    op.drop_index('ix_asset_conn_deleted_type', table_name='tableau_assets')
    op.drop_table('tableau_assets')
    op.drop_index('ix_issue_scan_severity', table_name='bi_health_scan_issues')
    op.drop_table('bi_health_scan_issues')
    op.drop_table('auth_user_group_members')
    op.drop_table('auth_group_permissions')
    op.drop_index('ix_publish_log_object', table_name='tableau_publish_logs')
    op.drop_index('ix_publish_log_conn_status', table_name='tableau_publish_logs')
    op.drop_table('tableau_publish_logs')
    op.drop_index('ix_field_semantic_status', table_name='tableau_field_semantics')
    op.drop_index('ix_field_semantic_reg_id', table_name='tableau_field_semantics')
    op.drop_index('ix_field_semantic_conn_id', table_name='tableau_field_semantics')
    op.drop_table('tableau_field_semantics')
    op.drop_index('ix_ds_semantic_status', table_name='tableau_datasource_semantics')
    op.drop_index('ix_ds_semantic_conn_id', table_name='tableau_datasource_semantics')
    op.drop_table('tableau_datasource_semantics')
    op.drop_table('tableau_connections')
    op.drop_table('bi_scan_logs')
    op.drop_index(op.f('ix_bi_rule_configs_rule_id'), table_name='bi_rule_configs')
    op.drop_table('bi_rule_configs')
    op.drop_table('bi_rule_change_logs')
    op.drop_table('bi_requirements')
    op.drop_table('bi_operation_logs')
    op.drop_index(op.f('ix_bi_health_scan_records_datasource_id'), table_name='bi_health_scan_records')
    op.drop_table('bi_health_scan_records')
    op.drop_table('bi_data_sources')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_auth_user_groups_name'), table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_table('ai_llm_configs')
    # ### end Alembic commands ###
