"""add_quality_tables

Revision ID: 7e5fa32da72b
Revises: 20260427_0001
Create Date: 2026-04-27 23:41:27.708702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e5fa32da72b'
down_revision: Union[str, None] = '20260427_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_api_tokens_prefix', 'auth_api_tokens', ['prefix'], unique=False)
    op.create_index('ix_api_tokens_token_hash', 'auth_api_tokens', ['token_hash'], unique=False)
    op.create_index('ix_api_tokens_user_id', 'auth_api_tokens', ['user_id'], unique=False)
    op.create_table('auth_password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_password_reset_tokens_user_id'), 'auth_password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_password_reset_tokens_token_hash', 'auth_password_reset_tokens', ['token_hash'], unique=False)
    op.create_index('ix_password_reset_tokens_user_id', 'auth_password_reset_tokens', ['user_id'], unique=False)
    op.drop_table('query_sessions')
    op.drop_index(op.f('ix_bi_dqc_dimension_scores_asset_id'), table_name='bi_dqc_dimension_scores')
    op.drop_index(op.f('ix_bi_dqc_dimension_scores_cycle_id'), table_name='bi_dqc_dimension_scores')
    op.drop_index(op.f('ix_dqc_dim_asset_dim_computed'), table_name='bi_dqc_dimension_scores')
    op.drop_index(op.f('ix_dqc_dim_cycle'), table_name='bi_dqc_dimension_scores')
    op.drop_index(op.f('ix_dqc_dim_signal'), table_name='bi_dqc_dimension_scores')
    op.drop_table('bi_dqc_dimension_scores')
    op.drop_index(op.f('ix_bi_dqc_asset_snapshots_asset_id'), table_name='bi_dqc_asset_snapshots')
    op.drop_index(op.f('ix_bi_dqc_asset_snapshots_cycle_id'), table_name='bi_dqc_asset_snapshots')
    op.drop_index(op.f('ix_dqc_snap_asset_computed'), table_name='bi_dqc_asset_snapshots')
    op.drop_index(op.f('ix_dqc_snap_cycle'), table_name='bi_dqc_asset_snapshots')
    op.drop_index(op.f('ix_dqc_snap_signal'), table_name='bi_dqc_asset_snapshots')
    op.drop_table('bi_dqc_asset_snapshots')
    op.drop_table('platform_settings')
    op.drop_table('mcp_debug_logs')
    op.drop_index(op.f('ix_bi_dqc_monitored_assets_datasource_id'), table_name='bi_dqc_monitored_assets')
    op.drop_index(op.f('ix_bi_dqc_monitored_assets_owner_id'), table_name='bi_dqc_monitored_assets')
    op.drop_index(op.f('ix_dqc_asset_owner'), table_name='bi_dqc_monitored_assets')
    op.drop_index(op.f('ix_dqc_asset_status'), table_name='bi_dqc_monitored_assets')
    op.drop_table('bi_dqc_monitored_assets')
    op.drop_index(op.f('ix_dqc_cycle_started'), table_name='bi_dqc_cycles')
    op.drop_index(op.f('ix_dqc_cycle_status_created'), table_name='bi_dqc_cycles')
    op.drop_table('bi_dqc_cycles')
    op.drop_table('query_error_events')
    op.drop_index(op.f('ix_bi_dqc_rule_results_asset_id'), table_name='bi_dqc_rule_results')
    op.drop_index(op.f('ix_bi_dqc_rule_results_cycle_id'), table_name='bi_dqc_rule_results')
    op.drop_index(op.f('ix_bi_dqc_rule_results_rule_id'), table_name='bi_dqc_rule_results')
    op.drop_index(op.f('ix_dqc_rres_asset_rule'), table_name='bi_dqc_rule_results')
    op.drop_index(op.f('ix_dqc_rres_cycle_asset'), table_name='bi_dqc_rule_results')
    op.drop_index(op.f('ix_dqc_rres_passed_executed'), table_name='bi_dqc_rule_results')
    op.drop_table('bi_dqc_rule_results')
    op.drop_index(op.f('ix_bi_dqc_quality_rules_asset_id'), table_name='bi_dqc_quality_rules')
    op.drop_index(op.f('ix_dqc_rule_asset_active'), table_name='bi_dqc_quality_rules')
    op.drop_index(op.f('ix_dqc_rule_asset_dim'), table_name='bi_dqc_quality_rules')
    op.drop_table('bi_dqc_quality_rules')
    op.drop_index(op.f('ix_ac_user'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_table('query_connected_app_secrets')
    op.drop_index(op.f('ix_acm_conv'), table_name='agent_conversation_messages')
    op.drop_index(op.f('ix_agent_conversation_messages_conversation_id'), table_name='agent_conversation_messages')
    op.drop_table('agent_conversation_messages')
    op.drop_table('query_messages')
    op.drop_index(op.f('ix_bi_dqc_llm_analyses_asset_id'), table_name='bi_dqc_llm_analyses')
    op.drop_index(op.f('ix_bi_dqc_llm_analyses_created_at'), table_name='bi_dqc_llm_analyses')
    op.drop_index(op.f('ix_bi_dqc_llm_analyses_cycle_id'), table_name='bi_dqc_llm_analyses')
    op.drop_index(op.f('ix_dqc_llm_asset_created'), table_name='bi_dqc_llm_analyses')
    op.drop_table('bi_dqc_llm_analyses')
    op.add_column('auth_refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('auth_refresh_tokens', sa.Column('user_agent', sa.String(length=512), nullable=True))
    op.drop_index(op.f('ix_bi_quality_results_datasource_id'), table_name='bi_quality_results')
    op.drop_index(op.f('ix_bi_quality_results_rule_id'), table_name='bi_quality_results')
    op.drop_index(op.f('ix_qres_ds_exec'), table_name='bi_quality_results')
    op.create_index('ix_qres_ds_exec', 'bi_quality_results', ['datasource_id', sa.literal_column('executed_at DESC')], unique=False)
    op.drop_index(op.f('ix_qres_rule_exec'), table_name='bi_quality_results')
    op.create_index('ix_qres_rule_exec', 'bi_quality_results', ['rule_id', sa.literal_column('executed_at DESC')], unique=False)
    op.drop_constraint(op.f('bi_quality_results_rule_id_fkey'), 'bi_quality_results', type_='foreignkey')
    op.create_foreign_key(None, 'bi_quality_results', 'bi_quality_rules', ['rule_id'], ['id'])
    op.drop_column('bi_quality_results', 'rule_type')
    op.drop_index(op.f('ix_bi_quality_rules_datasource_id'), table_name='bi_quality_rules')
    op.drop_constraint(op.f('bi_quality_rules_datasource_id_fkey'), 'bi_quality_rules', type_='foreignkey')
    op.create_foreign_key(None, 'bi_quality_rules', 'bi_data_sources', ['datasource_id'], ['id'])
    op.drop_index(op.f('ix_bi_quality_scores_datasource_id'), table_name='bi_quality_scores')
    op.drop_index(op.f('ix_qs_ds_scope'), table_name='bi_quality_scores')
    op.create_index('ix_qs_ds_scope', 'bi_quality_scores', ['datasource_id', 'scope_type', 'scope_name', sa.literal_column('calculated_at DESC')], unique=False)
    op.add_column('mcp_servers', sa.Column('site_name', sa.String(length=128), nullable=True))
    op.add_column('mcp_servers', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('mcp_servers', sa.Column('priority', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True))
    op.add_column('mcp_servers', sa.Column('health_status', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=True))
    op.add_column('mcp_servers', sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('CAST(0 AS INTEGER)'), nullable=True))
    op.add_column('tableau_field_semantics', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.add_column('tableau_field_semantics', sa.Column('embedding_model', sa.String(length=64), nullable=True))
    op.add_column('tableau_field_semantics', sa.Column('embedding_generated_at', sa.DateTime(), nullable=True))
    op.add_column('tableau_field_semantics', sa.Column('chunk_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tableau_field_semantics', 'chunk_text')
    op.drop_column('tableau_field_semantics', 'embedding_generated_at')
    op.drop_column('tableau_field_semantics', 'embedding_model')
    op.drop_column('tableau_field_semantics', 'embedding')
    op.drop_column('mcp_servers', 'consecutive_failures')
    op.drop_column('mcp_servers', 'health_status')
    op.drop_column('mcp_servers', 'priority')
    op.drop_column('mcp_servers', 'is_default')
    op.drop_column('mcp_servers', 'site_name')
    op.drop_index('ix_qs_ds_scope', table_name='bi_quality_scores')
    op.create_index(op.f('ix_qs_ds_scope'), 'bi_quality_scores', ['datasource_id', 'scope_type', 'scope_name', 'calculated_at'], unique=False)
    op.create_index(op.f('ix_bi_quality_scores_datasource_id'), 'bi_quality_scores', ['datasource_id'], unique=False)
    op.drop_constraint(None, 'bi_quality_rules', type_='foreignkey')
    op.create_foreign_key(op.f('bi_quality_rules_datasource_id_fkey'), 'bi_quality_rules', 'bi_data_sources', ['datasource_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_bi_quality_rules_datasource_id'), 'bi_quality_rules', ['datasource_id'], unique=False)
    op.add_column('bi_quality_results', sa.Column('rule_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bi_quality_results', type_='foreignkey')
    op.create_foreign_key(op.f('bi_quality_results_rule_id_fkey'), 'bi_quality_results', 'bi_quality_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_qres_rule_exec', table_name='bi_quality_results')
    op.create_index(op.f('ix_qres_rule_exec'), 'bi_quality_results', ['rule_id', 'executed_at'], unique=False)
    op.drop_index('ix_qres_ds_exec', table_name='bi_quality_results')
    op.create_index(op.f('ix_qres_ds_exec'), 'bi_quality_results', ['datasource_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_bi_quality_results_rule_id'), 'bi_quality_results', ['rule_id'], unique=False)
    op.create_index(op.f('ix_bi_quality_results_datasource_id'), 'bi_quality_results', ['datasource_id'], unique=False)
    op.drop_column('auth_refresh_tokens', 'user_agent')
    op.drop_column('auth_refresh_tokens', 'ip_address')
    op.create_table('bi_dqc_llm_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trigger', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('signal', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('root_cause', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fix_suggestion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fix_sql', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('suggested_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bi_dqc_llm_analyses_pkey'))
    )
    op.create_index(op.f('ix_dqc_llm_asset_created'), 'bi_dqc_llm_analyses', ['asset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bi_dqc_llm_analyses_cycle_id'), 'bi_dqc_llm_analyses', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_bi_dqc_llm_analyses_created_at'), 'bi_dqc_llm_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_bi_dqc_llm_analyses_asset_id'), 'bi_dqc_llm_analyses', ['asset_id'], unique=False)
    op.create_table('query_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_table', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datasource_luid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('query_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['tableau_connections.id'], name=op.f('query_messages_connection_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['query_sessions.id'], name=op.f('query_messages_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('query_messages_pkey'))
    )
    op.create_table('agent_conversation_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tools_used', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('steps_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_conversation_messages_pkey'))
    )
    op.create_index(op.f('ix_agent_conversation_messages_conversation_id'), 'agent_conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_acm_conv'), 'agent_conversation_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('query_connected_app_secrets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('secret_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['tableau_connections.id'], name=op.f('query_connected_app_secrets_connection_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['auth_users.id'], name=op.f('query_connected_app_secrets_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('query_connected_app_secrets_pkey'))
    )
    op.create_table('agent_conversations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_conversations_pkey'))
    )
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_ac_user'), 'agent_conversations', ['user_id', 'status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('bi_dqc_quality_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dimension', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('rule_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_system_suggested', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('suggested_by_llm_analysis_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['bi_dqc_monitored_assets.id'], name=op.f('bi_dqc_quality_rules_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bi_dqc_quality_rules_pkey'))
    )
    op.create_index(op.f('ix_dqc_rule_asset_dim'), 'bi_dqc_quality_rules', ['asset_id', 'dimension'], unique=False)
    op.create_index(op.f('ix_dqc_rule_asset_active'), 'bi_dqc_quality_rules', ['asset_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_bi_dqc_quality_rules_asset_id'), 'bi_dqc_quality_rules', ['asset_id'], unique=False)
    op.create_table('bi_dqc_rule_results',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actual_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expected_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'executed_at', name=op.f('pk_bi_dqc_rule_results'))
    )
    op.create_index(op.f('ix_dqc_rres_passed_executed'), 'bi_dqc_rule_results', ['passed', 'executed_at'], unique=False)
    op.create_index(op.f('ix_dqc_rres_cycle_asset'), 'bi_dqc_rule_results', ['cycle_id', 'asset_id'], unique=False)
    op.create_index(op.f('ix_dqc_rres_asset_rule'), 'bi_dqc_rule_results', ['asset_id', 'rule_id'], unique=False)
    op.create_index(op.f('ix_bi_dqc_rule_results_rule_id'), 'bi_dqc_rule_results', ['rule_id'], unique=False)
    op.create_index(op.f('ix_bi_dqc_rule_results_cycle_id'), 'bi_dqc_rule_results', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_bi_dqc_rule_results_asset_id'), 'bi_dqc_rule_results', ['asset_id'], unique=False)
    op.create_table('query_error_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('error_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['tableau_connections.id'], name=op.f('query_error_events_connection_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('query_error_events_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('query_error_events_pkey'))
    )
    op.create_table('bi_dqc_cycles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=16), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=16), server_default=sa.text("'full'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assets_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('assets_processed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('assets_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('rules_executed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('p0_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('p1_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('triggered_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bi_dqc_cycles_pkey'))
    )
    op.create_index(op.f('ix_dqc_cycle_status_created'), 'bi_dqc_cycles', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_dqc_cycle_started'), 'bi_dqc_cycles', ['started_at'], unique=False)
    op.create_table('bi_dqc_monitored_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datasource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dimension_weights', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"accuracy": 0.1667, "validity": 0.1667, "timeliness": 0.1667, "uniqueness": 0.1666, "consistency": 0.1666, "completeness": 0.1667}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('signal_thresholds', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"drift_p0": 20, "drift_p1": 10, "p0_score": 60, "p1_score": 80, "confidence_p0": 60, "confidence_p1": 80}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'enabled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['bi_data_sources.id'], name=op.f('bi_dqc_monitored_assets_datasource_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bi_dqc_monitored_assets_pkey')),
    sa.UniqueConstraint('datasource_id', 'schema_name', 'table_name', name=op.f('uq_dqc_asset_ds_sch_tbl'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_dqc_asset_status'), 'bi_dqc_monitored_assets', ['status'], unique=False)
    op.create_index(op.f('ix_dqc_asset_owner'), 'bi_dqc_monitored_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_bi_dqc_monitored_assets_owner_id'), 'bi_dqc_monitored_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_bi_dqc_monitored_assets_datasource_id'), 'bi_dqc_monitored_assets', ['datasource_id'], unique=False)
    op.create_table('mcp_debug_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('arguments_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('result_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mcp_debug_logs_pkey'))
    )
    op.create_table('platform_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('platform_subtitle', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('favicon_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_platform_settings_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_settings_pkey'))
    )
    op.create_table('bi_dqc_asset_snapshots',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('signal', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('prev_signal', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('dimension_signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('row_count_snapshot', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'computed_at', name=op.f('pk_bi_dqc_asset_snapshots'))
    )
    op.create_index(op.f('ix_dqc_snap_signal'), 'bi_dqc_asset_snapshots', ['signal'], unique=False)
    op.create_index(op.f('ix_dqc_snap_cycle'), 'bi_dqc_asset_snapshots', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_dqc_snap_asset_computed'), 'bi_dqc_asset_snapshots', ['asset_id', 'computed_at'], unique=False)
    op.create_index(op.f('ix_bi_dqc_asset_snapshots_cycle_id'), 'bi_dqc_asset_snapshots', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_bi_dqc_asset_snapshots_asset_id'), 'bi_dqc_asset_snapshots', ['asset_id'], unique=False)
    op.create_table('bi_dqc_dimension_scores',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('signal', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('prev_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('drift_24h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('drift_vs_7d_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rules_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('rules_passed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('rules_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'computed_at', name=op.f('pk_bi_dqc_dimension_scores'))
    )
    op.create_index(op.f('ix_dqc_dim_signal'), 'bi_dqc_dimension_scores', ['signal'], unique=False)
    op.create_index(op.f('ix_dqc_dim_cycle'), 'bi_dqc_dimension_scores', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_dqc_dim_asset_dim_computed'), 'bi_dqc_dimension_scores', ['asset_id', 'dimension', 'computed_at'], unique=False)
    op.create_index(op.f('ix_bi_dqc_dimension_scores_cycle_id'), 'bi_dqc_dimension_scores', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_bi_dqc_dimension_scores_asset_id'), 'bi_dqc_dimension_scores', ['asset_id'], unique=False)
    op.create_table('query_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('query_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('query_sessions_pkey'))
    )
    op.drop_index('ix_password_reset_tokens_user_id', table_name='auth_password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_token_hash', table_name='auth_password_reset_tokens')
    op.drop_index(op.f('ix_auth_password_reset_tokens_user_id'), table_name='auth_password_reset_tokens')
    op.drop_table('auth_password_reset_tokens')
    op.drop_index('ix_api_tokens_user_id', table_name='auth_api_tokens')
    op.drop_index('ix_api_tokens_token_hash', table_name='auth_api_tokens')
    op.drop_index('ix_api_tokens_prefix', table_name='auth_api_tokens')
    op.drop_table('auth_api_tokens')
    # ### end Alembic commands ###
