"""Tableau 管理 API
"""
import json
import logging
from typing import Any, AsyncGenerator, List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy import orm as sa_orm
from sqlalchemy.orm import Session
import sqlalchemy as sa

from app.core.crypto import get_tableau_crypto
from app.core.database import get_db  # 导入中央数据库依赖
from app.core.dependencies import get_current_user, require_roles
from app.utils.auth import verify_connection_access  # 导入统一的权限验证函数
from services.tableau.field_reconciliation import queryability_status, summarize_field_capabilities
from services.tableau.models import TableauDatabase, TableauSyncLog
from services.tableau.models import TableauConnection as TableauConnectionModel
from services.tableau.mcp_binding_service import TableauMcpBindingService
from services.tableau.sync_service import TableauSyncService
from services.audit.audit_service import log_action

router = APIRouter()

logger = logging.getLogger(__name__)

_crypto = get_tableau_crypto()
_encrypt = _crypto.encrypt
_decrypt = _crypto.decrypt


def _format_tableau_dt(value) -> Optional[str]:
    return value.strftime("%Y-%m-%d %H:%M:%S") if hasattr(value, "strftime") else None


def _datasource_self_payload(asset) -> dict:
    return {
        "id": asset.id,
        "tableau_id": asset.tableau_id,
        "name": asset.name,
        "project_name": asset.project_name,
        "connection_id": asset.connection_id,
        "content_url": asset.content_url,
        "web_url": asset.web_url,
    }


def _field_metadata_value(field, *keys):
    metadata = field.metadata_json or {}
    if not isinstance(metadata, dict):
        return None
    for key in keys:
        if key in metadata:
            return metadata[key]
    return None


def _clean_json_value(value: Any) -> Any:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, (list, dict)):
        return value
    return None


def _field_mcp_payload(field) -> dict | None:
    metadata = getattr(field, "metadata_json", None) or {}
    if not isinstance(metadata, dict):
        metadata = {}
    payload = {
        "name": metadata.get("name"),
        "dataType": metadata.get("dataType"),
        "role": metadata.get("role"),
        "columnClass": metadata.get("columnClass"),
        "logicalTableId": metadata.get("logicalTableId"),
        "dataCategory": metadata.get("dataCategory"),
        "defaultAggregation": metadata.get("defaultAggregation"),
        "defaultFormat": metadata.get("defaultFormat"),
        "formula": metadata.get("formula"),
        "isAutoGenerated": metadata.get("isAutoGenerated"),
        "hasUserReference": metadata.get("hasUserReference"),
        "isHidden": metadata.get("isHidden"),
        "fullyQualifiedName": metadata.get("fullyQualifiedName"),
    }
    _mcp_exclusive = {'columnClass', 'logicalTableId', 'dataCategory', 'defaultAggregation',
                      'defaultFormat', 'formula', 'isAutoGenerated', 'hasUserReference'}
    return payload if any(payload.get(k) is not None for k in _mcp_exclusive) else None


def _datasource_field_api_payload(field, *, source: str = "mcp_cache") -> dict:
    description = _clean_json_value(getattr(field, "description", None)) or ""
    ai_description = _clean_json_value(getattr(field, "ai_description", None))
    mcp_queryable = getattr(field, "mcp_queryable", None)
    return {
        "name": _clean_json_value(getattr(field, "field_name", None)) or "",
        "field": _clean_json_value(getattr(field, "field_name", None)) or "",
        "caption": _clean_json_value(getattr(field, "field_caption", None)) or "",
        "data_type": _clean_json_value(getattr(field, "data_type", None)) or "STRING",
        "role": _clean_json_value(getattr(field, "role", None)) or "dimension",
        "description": description,
        "meaning": ai_description or description,
        "aggregation": _clean_json_value(getattr(field, "aggregation", None)),
        "formula": _clean_json_value(getattr(field, "formula", None)),
        "is_calculated": bool(_clean_json_value(getattr(field, "is_calculated", None))),
        "source": source,
        "fetched_at": _format_tableau_dt(getattr(field, "fetched_at", None)),
        "mcp_queryable": mcp_queryable if isinstance(mcp_queryable, bool) else None,
        "mcp_field_name": _clean_json_value(getattr(field, "mcp_field_name", None)),
        "mcp_field_caption": _clean_json_value(getattr(field, "mcp_field_caption", None)),
        "mcp_checked_at": _format_tableau_dt(getattr(field, "mcp_checked_at", None)),
        "mcp_last_error": _clean_json_value(getattr(field, "mcp_last_error", None)),
        "queryability_status": queryability_status(field),
        "mcp": _field_mcp_payload(field),
    }


def _fields_response_payload(fields, *, cache_status: str, source: str = "mcp_cache", **extra) -> dict:
    field_list = list(fields or [])
    payload = {
        "total": len(field_list),
        "cache_status": cache_status,
        "fields": [_datasource_field_api_payload(f, source=source) for f in field_list],
    }
    payload.update(summarize_field_capabilities(field_list))
    payload.update(extra)
    return payload


# _db_path 函数不再需要，因为 TableauDatabase 将使用中央配置
# def _db_path():
#     return str(Path(__file__).parent.parent.parent.parent / "data" / "tableau.db")


# require_admin_or_data_admin 已经通过 app.core.dependencies.require_roles 替代
# def require_admin_or_data_admin(request: Request) -> dict:
#     """仅管理员或数据管理员可访问"""
#     user = get_current_user(request)
#     if user["role"] not in ("admin", "data_admin"):
#         raise HTTPException(status_code=403, detail="需要管理员或数据管理员权限")
#     return user

# _verify_connection_access 已经提取到 app.utils.auth.py
# def _verify_connection_access(connection_id: int, user: dict, _db: TableauDatabase) -> None:
#     """验证用户有权访问指定连接（IDOR 修复）"""
#     conn = _db.get_connection(connection_id)
#     if not conn:
#         raise HTTPException(status_code=404, detail="连接不存在")
#     # admin 可访问所有连接，非 admin 只能访问自己的
#     if user["role"] != "admin" and conn.owner_id != user["id"]:
#         raise HTTPException(status_code=403, detail="无权访问该连接")


# --- Pydantic Models ---

class CreateConnectionRequest(BaseModel):
    name: str
    server_url: str
    site: str
    api_version: str = "3.21"
    connection_type: str = "mcp"  # 'mcp' or 'tsc'
    token_name: str
    token_value: str
    auto_sync_enabled: bool = False
    schedule_id: Optional[int] = None
    agent_enabled: bool = False


class UpdateConnectionRequest(BaseModel):
    name: Optional[str] = None
    server_url: Optional[str] = None
    site: Optional[str] = None
    api_version: Optional[str] = None
    connection_type: Optional[str] = None
    token_name: Optional[str] = None
    token_value: Optional[str] = None
    is_active: Optional[bool] = None
    auto_sync_enabled: Optional[bool] = None
    sync_interval_hours: Optional[int] = None
    schedule_id: Optional[int] = None
    agent_enabled: Optional[bool] = None


# --- REST API 直连测试（MCP 模式） ---

def _test_connection_rest(server_url: str, site: str, token_name: str,
                          token_value: str, api_version: str = "3.21") -> dict:
    """通过 REST API 直接测试 Tableau 连接（不依赖 TSC 库）"""
    import requests
    url = f"{server_url.rstrip('/')}/api/{api_version}/auth/signin"
    payload = {
        "credentials": {
            "personalAccessTokenName": token_name,
            "personalAccessTokenSecret": token_value,
            "site": {"contentUrl": site}
        }
    }
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    try:
        resp = requests.post(url, json=payload, headers=headers, timeout=15)
        if resp.status_code == 200:
            data = resp.json()
            token = data.get("credentials", {}).get("token", "")
            site_id = data.get("credentials", {}).get("site", {}).get("id", "")
            if not token:
                return {"success": False, "message": "REST API 认证失败：未获取到 token"}
            # Sign out 清理 session
            try:
                requests.post(
                    f"{server_url.rstrip('/')}/api/{api_version}/auth/signout",
                    headers={"X-Tableau-Auth": token},
                    timeout=5
                )
            except Exception as e:
                logger.debug("Tableau signout failed (non-critical): %s", e)
            return {"success": True, "message": f"REST API 连接成功 (site_id={site_id})"}
        else:
            detail = resp.text[:200]
            return {"success": False, "message": f"REST API 认证失败 (HTTP {resp.status_code}): {detail}"}
    except Exception as e:
        if "Timeout" in type(e).__name__:
            return {"success": False, "message": "连接超时，请检查 Server URL 是否可达"}
        if "ConnectionError" in type(e).__name__:
            return {"success": False, "message": "无法连接到服务器，请检查 URL"}
        return {"success": False, "message": f"REST API 测试失败: {str(e)}"}


def _normalize_connection_key(server_url: str, site: str) -> tuple[str, str]:
    return ((server_url or "").strip().rstrip("/").lower(), (site or "").strip().strip("/").lower())


def _find_duplicate_connection(
    db: Session,
    *,
    server_url: str,
    site: str,
    owner_id: int,
    exclude_id: Optional[int] = None,
) -> Optional[TableauConnectionModel]:
    target = _normalize_connection_key(server_url, site)
    query = db.query(TableauConnectionModel).filter(TableauConnectionModel.owner_id == owner_id)
    if exclude_id is not None:
        query = query.filter(TableauConnectionModel.id != exclude_id)
    for conn in query.all():
        if _normalize_connection_key(conn.server_url, conn.site) == target:
            return conn
    return None


def _binding_payload(binding_result: dict) -> dict:
    return {
        "mcp_server_id": binding_result.get("mcp_server_id"),
        "server_url": binding_result.get("server_url"),
        "binding_status": binding_result.get("binding_status") or binding_result.get("status"),
        "health_status": binding_result.get("health_status"),
        "last_error": binding_result.get("last_error"),
    }


def _refresh_binding_health_after_commit(
    db: Session,
    *,
    connection_id: int,
    user_id: int,
    binding: dict,
) -> dict:
    if binding.get("binding_status") == "disabled" or not binding.get("mcp_server_id"):
        return binding

    binding = TableauMcpBindingService(db).refresh_health_for_connection(
        connection_id=connection_id,
        user_id=user_id,
    )
    db.commit()
    return binding


# --- Endpoints ---

@router.get("/connections")
async def list_connections(request: Request, db: Session = Depends(get_db), include_inactive: bool = False):
    """获取 Tableau 连接列表"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    if user["role"] == "admin":
        connections = _db.get_all_connections(include_inactive=include_inactive)
    else:
        connections = _db.get_all_connections(owner_id=user["id"], include_inactive=include_inactive)

    connection_dicts = [c.to_dict(db) for c in connections]

    # 仅在没有真实 tableau_connections 时保留 10000+ 虚拟连接兜底。
    # 正常路径应由 MCP 配置创建/更新时桥接到 tableau_connections。
    try:
        from services.mcp.models import McpServer
        if connection_dicts:
            active_mcp_count = db.query(McpServer).filter(
                McpServer.type == "tableau",
                McpServer.is_active == True,
            ).count()
            if active_mcp_count:
                logger.info(
                    "Skipping %d virtual Tableau MCP connection fallback rows because real tableau_connections exist",
                    active_mcp_count,
                )
        else:
            from app.api.mcp_configs import _normalize_tableau_credentials
            mcp_servers = db.query(McpServer).filter(
                McpServer.type == "tableau",
                McpServer.is_active == True,
            ).all()

            for mcp in mcp_servers:
                try:
                    creds = _normalize_tableau_credentials(mcp.credentials)
                except Exception as exc:
                    logger.warning(
                        "Skipping virtual Tableau MCP fallback for mcp_server id=%s name=%s: credential decrypt failed: %s",
                        mcp.id,
                        mcp.name,
                        exc,
                    )
                    continue
                if not (creds.get("pat_value") and creds.get("tableau_server") and creds.get("pat_name")):
                    logger.warning(
                        "Skipping virtual Tableau MCP fallback for mcp_server id=%s name=%s: incomplete credentials",
                        mcp.id,
                        mcp.name,
                    )
                    continue
                connection_dicts.append({
                    "id": 10000 + mcp.id,
                    "name": mcp.name,
                    "server_url": creds.get("tableau_server") or mcp.server_url or "",
                    "site": creds.get("site_name") or "",
                    "api_version": "3.21",
                    "connection_type": "mcp",
                    "token_name": creds.get("pat_name") or "",
                    "owner_id": None,
                    "is_active": True,
                    "auto_sync_enabled": False,
                    "sync_interval_hours": 24,
                    "last_test_at": None,
                    "last_test_success": None,
                    "last_test_message": "virtual MCP fallback; bridge to tableau_connections pending",
                    "last_sync_at": None,
                    "last_sync_duration_sec": None,
                    "sync_status": "idle",
                    "mcp_direct_enabled": True,
                    "mcp_server_url": mcp.server_url or "",
                    "next_sync_at": None,
                    "created_at": mcp.created_at.strftime("%Y-%m-%d %H:%M:%S") if mcp.created_at else None,
                    "updated_at": mcp.updated_at.strftime("%Y-%m-%d %H:%M:%S") if mcp.updated_at else None,
                    "source": "mcp_virtual_fallback",
                })
    except Exception:
        logger.exception("从 mcp_servers 聚合 Tableau 连接时出错，返回仅 tableau_connections 的结果")

    # 修正 stale sync_status（基于最新 TableauSyncLog）
    # 场景：Celery 任务完成但未更新 connections 表的 sync_status
    # 规则：连接 sync_status 应与最新 log status 对齐
    #   log=running  → 连接保持 running（正常进行中）
    #   log=success  → 连接应为 idle
    #   log=failed/partial → 连接应为 failed
    try:
        running_conn_ids = [c.id for c in connections if c.sync_status == "running"]
        if running_conn_ids:
            updates = {}  # conn_id -> new status
            for conn_id in running_conn_ids:
                max_log = (
                    db.query(sa.func.max(TableauSyncLog.id))
                    .filter(TableauSyncLog.connection_id == conn_id)
                    .scalar()
                )
                if max_log:
                    log = db.query(TableauSyncLog).filter(TableauSyncLog.id == max_log).first()
                    if log and log.status != "running":
                        new_status = "idle" if log.status == "success" else "failed"
                        updates[conn_id] = new_status
                        logger.info(f"[sync_status reconciliation] conn_id={conn_id} log_status={log.status} → {new_status}")
            if updates:
                for conn_id, new_status in updates.items():
                    db.query(TableauConnectionModel).filter(
                        TableauConnectionModel.id == conn_id
                    ).update(
                        {TableauConnectionModel.sync_status: new_status},
                        synchronize_session=False,
                    )
                db.commit()
                # 重新查询更新后的连接
                if user["role"] == "admin":
                    connections = _db.get_all_connections(include_inactive=include_inactive)
                else:
                    connections = _db.get_all_connections(owner_id=user["id"], include_inactive=include_inactive)
                connection_dicts = [c.to_dict(db) for c in connections]
    except Exception:
        logger.exception("修正 stale sync_status 时出错")

    return {"connections": connection_dicts, "total": len(connection_dicts)}


@router.post("/connections", status_code=201)
async def create_connection(
    req: CreateConnectionRequest,
    current_user: dict = Depends(require_roles(["admin", "data_admin"])),
    db: Session = Depends(get_db),
):
    """创建 Tableau 连接"""
    if req.connection_type not in ("mcp", "tsc"):
        raise HTTPException(status_code=400, detail="connection_type 必须为 'mcp' 或 'tsc'")

    duplicate = _find_duplicate_connection(
        db,
        server_url=req.server_url,
        site=req.site,
        owner_id=current_user["id"],
    )
    if duplicate is not None:
        raise HTTPException(
            status_code=409,
            detail={"code": "TAB_409", "message": "该 Tableau 站点已接入，请复用已有连接"},
        )

    if req.connection_type == "mcp":
        test_result = _test_connection_rest(
            req.server_url,
            req.site,
            req.token_name,
            req.token_value,
            req.api_version,
        )
        if not test_result.get("success"):
            raise HTTPException(
                status_code=400,
                detail={"code": "TAB_REST_001", "message": test_result.get("message", "Tableau REST 测试失败")},
            )

    encrypted_token = _encrypt(req.token_value)
    conn = TableauConnectionModel(
        name=req.name,
        server_url=req.server_url,
        site=req.site,
        token_name=req.token_name,
        token_encrypted=encrypted_token,
        owner_id=current_user["id"],
        api_version=req.api_version,
        connection_type=req.connection_type,
        auto_sync_enabled=req.auto_sync_enabled,
        schedule_id=req.schedule_id if req.auto_sync_enabled else None,
    )
    db.add(conn)
    db.flush()

    binding = TableauMcpBindingService(db).upsert_for_connection(
        connection=conn,
        enabled=req.agent_enabled,
        owner_id=current_user["id"],
        health_check=False,
    )
    db.commit()
    binding = _refresh_binding_health_after_commit(
        db,
        connection_id=conn.id,
        user_id=current_user["id"],
        binding=binding,
    )
    db.refresh(conn)

    log_action(current_user["id"], current_user.get("username", ""), "create", "tableau_connection", conn.id,
               after_state={"name": conn.name, "server_url": conn.server_url, "site": conn.site})
    payload = conn.to_dict(db)
    payload["mcp_binding"] = _binding_payload(binding)
    return {"connection": payload, "message": "连接创建成功"}


@router.put("/connections/{conn_id}")
async def update_connection(
    conn_id: int,
    req: UpdateConnectionRequest,
    current_user: dict = Depends(require_roles(["admin", "data_admin"])),
    db: Session = Depends(get_db),
):
    """更新 Tableau 连接"""
    _db = TableauDatabase(session=db)

    # 使用统一的权限验证函数
    verify_connection_access(conn_id, current_user, db)

    current = _db.get_connection(conn_id)
    if not current:
        raise HTTPException(status_code=404, detail="连接不存在")

    update_data = req.model_dump(exclude_unset=True)
    agent_enabled = update_data.pop("agent_enabled", None)
    new_server_url = update_data.get("server_url", current.server_url)
    new_site = update_data.get("site", current.site)
    connection_key_changed = (
        _normalize_connection_key(new_server_url, new_site)
        != _normalize_connection_key(current.server_url, current.site)
    )
    if connection_key_changed:
        duplicate = _find_duplicate_connection(
            db,
            server_url=new_server_url,
            site=new_site,
            owner_id=current.owner_id,
            exclude_id=conn_id,
        )
        if duplicate is not None:
            raise HTTPException(
                status_code=409,
                detail={"code": "TAB_409", "message": "该 Tableau 站点已接入，请复用已有连接"},
            )

    token_for_test = None
    if "token_value" in update_data and update_data["token_value"]:
        # 用户提供了新 token_value，同时更新 token_name 和加密后的 token
        token_for_test = update_data["token_value"]
        update_data["token_encrypted"] = _encrypt(update_data.pop("token_value"))
        if req.token_name:
            update_data["token_name"] = req.token_name
    elif "token_value" in update_data and not update_data["token_value"]:
        # token_value 为空字符串，不更新 token 相关字段
        update_data.pop("token_value", None)
        update_data.pop("token_name", None)

    should_retest = (
        connection_key_changed
        or token_for_test is not None
        or ("api_version" in update_data and update_data["api_version"] != current.api_version)
        or ("token_name" in update_data and update_data["token_name"] != current.token_name)
    )
    if should_retest and current.connection_type == "mcp":
        test_token = token_for_test
        if test_token is None:
            test_token = _decrypt(current.token_encrypted)
        test_result = _test_connection_rest(
            new_server_url,
            new_site,
            update_data.get("token_name", current.token_name),
            test_token,
            update_data.get("api_version", current.api_version),
        )
        if not test_result.get("success"):
            raise HTTPException(
                status_code=400,
                detail={"code": "TAB_REST_001", "message": test_result.get("message", "Tableau REST 测试失败")},
            )

    for key, value in update_data.items():
        if hasattr(current, key) and value is not None:
            setattr(current, key, value)

    if current.is_active is False:
        agent_enabled = False
    if agent_enabled is None:
        agent_enabled = bool(current.mcp_direct_enabled)

    binding = TableauMcpBindingService(db).upsert_for_connection(
        connection=current,
        enabled=bool(agent_enabled),
        owner_id=current_user["id"],
        health_check=False,
    )
    db.commit()
    binding = _refresh_binding_health_after_commit(
        db,
        connection_id=current.id,
        user_id=current_user["id"],
        binding=binding,
    )
    db.refresh(current)

    log_action(current_user["id"], current_user.get("username", ""), "update", "tableau_connection", conn_id)
    payload = current.to_dict(db)
    payload["mcp_binding"] = _binding_payload(binding)
    return {"connection": payload, "message": "连接更新成功"}


@router.delete("/connections/{conn_id}")
async def delete_connection(
    conn_id: int,
    current_user: dict = Depends(require_roles(["admin", "data_admin"])),
    db: Session = Depends(get_db),
):
    """删除 Tableau 连接"""
    _db = TableauDatabase(session=db)

    # 使用统一的权限验证函数
    verify_connection_access(conn_id, current_user, db)

    # 优先从 tableau_connections 删除
    deleted = _db.delete_connection(conn_id)

    # 若 tableau_connections 中不存在（虚拟连接 ID = 10000 + mcp_server.id），
    # 则从 mcp_servers 表删除
    if not deleted and conn_id > 10000:
        from services.mcp.models import McpServer
        mcp_id = conn_id - 10000
        mcp = db.query(McpServer).filter(McpServer.id == mcp_id).first()
        if mcp and mcp.type == "tableau":
            db.delete(mcp)
            db.commit()
            deleted = True

    if not deleted:
        raise HTTPException(status_code=404, detail="连接不存在")

    log_action(current_user["id"], current_user.get("username", ""), "delete", "tableau_connection", conn_id)
    return {"message": "连接已删除"}


@router.post("/connections/{conn_id}/test")
async def test_connection(
    conn_id: int,
    current_user: dict = Depends(require_roles(["admin", "data_admin"])),
    db: Session = Depends(get_db),
):
    """测试 Tableau 连接"""
    _db = TableauDatabase(session=db)

    # 使用统一的权限验证函数
    verify_connection_access(conn_id, current_user, db)

    conn = _db.get_connection(conn_id)
    if not conn:
        raise HTTPException(status_code=404, detail="连接不存在")

    from cryptography.fernet import InvalidToken as FernetInvalidToken
    try:
        decrypted_token = _decrypt(conn.token_encrypted)
    except FernetInvalidToken:
        msg = "Token 解密失败：加密密钥可能已变更，请重新保存 PAT Token"
        _db.update_connection_health(conn_id, False, msg)
        return {"success": False, "message": msg}
    except Exception as e:
        msg = f"Token 解密失败：{e}"
        _db.update_connection_health(conn_id, False, msg)
        return {"success": False, "message": msg}

    # MCP 模式：通过 REST API 直连测试
    if getattr(conn, "connection_type", "mcp") == "mcp":
        result = _test_connection_rest(
            server_url=conn.server_url,
            site=conn.site,
            token_name=conn.token_name,
            token_value=decrypted_token,
            api_version=conn.api_version
        )
        _db.update_connection_health(conn_id, result["success"], result["message"])
        return result

    # TSC 模式：通过 tableauserverclient 库测试
    try:
        service = TableauSyncService(
            server_url=conn.server_url,
            site=conn.site,
            token_name=conn.token_name,
            token_value=decrypted_token,
            api_version=conn.api_version
        )
        try:
            result = service.test_connection()
            # 保存测试结果到数据库
            _db.update_connection_health(conn_id, result.get("success", False), result.get("message", ""))
            return result
        finally:
            service.disconnect()
    except Exception as e:
        error_msg = str(e)
        # 保存测试失败结果到数据库
        _db.update_connection_health(conn_id, False, f"测试失败: {error_msg}")
        return {"success": False, "message": f"测试失败: {error_msg}"}


# @router.post("/connections/{conn_id}/sync")  # Moved to ~line 540 with degraded check (Spec 13 §3.4 T2)


@router.get("/assets")
async def list_assets(
    request: Request,
    connection_id: int = Query(..., description="连接 ID"),
    asset_type: Optional[str] = Query(None, description="资产类型: workbook, view, datasource"),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """获取资产列表（分页）"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    # 验证用户有权访问该连接
    verify_connection_access(connection_id, user, db)

    assets, total = _db.get_assets(
        connection_id=connection_id,
        asset_type=asset_type,
        page=page,
        page_size=page_size
    )

    return {
        "assets": [a.to_dict() for a in assets],
        "total": total,
        "page": page,
        "page_size": page_size,
        "pages": (total + page_size - 1) // page_size
    }


@router.get("/assets/search")
async def search_assets(
    request: Request,
    q: str = Query(..., min_length=1, description="搜索关键词"),
    connection_id: Optional[int] = Query(None),
    asset_type: Optional[str] = Query(None),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """搜索资产。

    多租户隔离约束（Spec 07 §3.3.2 P0 IDOR 修复）：
    - admin 用户：可不指定 connection_id（搜索所有可访问连接）。
    - 非 admin 用户：
        - 指定 connection_id：仅返回该连接下的资产（需有访问权）。
        - 未指定 connection_id：强制限定为当前用户自己创建的连接（owner_id 过滤）。
    """
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    # 如果指定了 connection_id，验证用户有权访问
    if connection_id is not None:
        verify_connection_access(connection_id, user, db)

    # 非 admin 且未指定 connection_id 时，强制按 owner_id 过滤（IDOR 防护）
    owner_id_filter: Optional[int] = None
    if user["role"] != "admin" and connection_id is None:
        owner_id_filter = user["id"]

    assets, total = _db.search_assets(
        connection_id=connection_id,
        query=q,
        asset_type=asset_type,
        page=page,
        page_size=page_size,
        owner_id=owner_id_filter,
    )

    # 批量加载连接信息，为每个资产注入 server_url / site（供前端构造 Tableau 跳转链接）
    from services.tableau.models import TableauConnection as _TC
    conn_ids = list({a.connection_id for a in assets})
    conn_map = {}
    if conn_ids:
        conns = db.query(_TC).filter(_TC.id.in_(conn_ids)).all()
        conn_map = {c.id: c for c in conns}

    asset_dicts = []
    for a in assets:
        d = a.to_dict()
        conn = conn_map.get(a.connection_id)
        if conn:
            d['server_url'] = conn.server_url
            d['site'] = conn.site or ''
        asset_dicts.append(d)

    return {
        "assets": asset_dicts,
        "total": total,
        "page": page,
        "page_size": page_size
    }


@router.get("/assets/{asset_id}")
async def get_asset(asset_id: int, request: Request, db: Session = Depends(get_db)):
    """获取资产详情"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(status_code=404, detail="资产不存在")

    # 验证用户有权访问该资产所属的连接
    verify_connection_access(asset.connection_id, user, db)

    result = asset.to_dict()

    # 获取关联的数据源
    datasources = _db.get_asset_datasources(asset_id)
    result["datasources"] = [ds.to_dict() for ds in datasources]

    if asset.asset_type == "datasource":
        result["datasource_self"] = _datasource_self_payload(asset)
        actual_field_count = _db.get_datasource_field_count(asset_id)
        if asset.field_count != actual_field_count:
            _db.update_asset_field_count(asset_id, actual_field_count)
        result["field_count"] = actual_field_count

    # 获取连接信息（含 server_url 用于跳转链接）
    conn = _db.get_connection(asset.connection_id)
    if conn:
        result["server_url"] = conn.server_url
        result["site"] = conn.site or ""

    return result


@router.get("/projects")
async def get_projects(
    request: Request,
    connection_id: int = Query(..., description="连接 ID"),
    db: Session = Depends(get_db)
):
    """获取项目树"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    # 验证用户有权访问该连接
    verify_connection_access(connection_id, user, db)

    projects = _db.get_project_tree(connection_id)
    return {"projects": projects}


# --- Sync Logs (Phase 2a) ---

@router.get("/sync-logs")
async def list_all_sync_logs(
    request: Request,
    connection_id: Optional[int] = Query(None),
    status: Optional[str] = Query(None),
    start_date: Optional[str] = Query(None),
    end_date: Optional[str] = Query(None),
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db),
):
    """跨连接获取同步日志列表（admin/data_admin 可查所有，其他角色须指定自己有权访问的 connection_id）"""
    user = get_current_user(request, db)
    is_privileged = user.get("role") in ("admin", "data_admin")

    if not is_privileged:
        if connection_id is None:
            raise HTTPException(status_code=403, detail="查看全部同步日志需要管理员权限，请指定 connection_id")
        # 验证当前用户对该连接有访问权
        verify_connection_access(connection_id, user, db)
    _db = TableauDatabase(session=db)
    logs, total = _db.get_all_sync_logs(
        connection_id=connection_id,
        status=status,
        start_date=start_date,
        end_date=end_date,
        page=page,
        page_size=page_size,
    )
    return {
        "logs": logs,
        "total": total,
        "page": page,
        "page_size": page_size,
        "pages": (total + page_size - 1) // page_size,
    }


@router.get("/connections/{conn_id}/sync-logs")
async def list_sync_logs(
    conn_id: int,
    request: Request,
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """获取同步日志列表"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)
    verify_connection_access(conn_id, user, db)

    logs, total = _db.get_sync_logs(conn_id, page=page, page_size=page_size)
    return {
        "logs": [log.to_dict() for log in logs],
        "total": total,
        "page": page,
        "page_size": page_size,
        "pages": (total + page_size - 1) // page_size,
    }


@router.get("/connections/{conn_id}/sync-logs/{log_id}")
async def get_sync_log(conn_id: int, log_id: int, request: Request, db: Session = Depends(get_db)):
    """获取同步日志详情"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)
    verify_connection_access(conn_id, user, db)

    log = _db.get_sync_log(log_id)
    if not log or log.connection_id != conn_id:
        raise HTTPException(status_code=404, detail="同步日志不存在")
    return log.to_dict()


@router.get("/connections/{conn_id}/sync-status")
async def get_sync_status(conn_id: int, request: Request, db: Session = Depends(get_db)):
    """获取连接同步状态"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)
    verify_connection_access(conn_id, user, db)

    conn = _db.get_connection(conn_id)
    if not conn:
        raise HTTPException(status_code=404, detail="连接不存在")

    next_sync_at = None
    if conn.auto_sync_enabled:
        from datetime import datetime
        from services.tasks.models import BiSyncTask
        next_task = (
            db.query(BiSyncTask)
            .filter(
                BiSyncTask.connection_id == conn_id,
                BiSyncTask.status == "pending",
                BiSyncTask.scheduled_at >= datetime.now(),
            )
            .order_by(BiSyncTask.scheduled_at)
            .first()
        )
        next_sync_at = (
            next_task.scheduled_at.strftime("%Y-%m-%d %H:%M:%S")
            if next_task else "待规划"
        )

    return {
        "status": conn.sync_status or "idle",
        "last_sync_at": conn.last_sync_at.strftime("%Y-%m-%d %H:%M:%S") if conn.last_sync_at else None,
        "last_sync_duration_sec": conn.last_sync_duration_sec,
        "auto_sync_enabled": conn.auto_sync_enabled,
        "sync_interval_hours": conn.sync_interval_hours,
        "next_sync_at": next_sync_at,
    }


# ── Spec 13 §3.4: MCP Offline Degradation ────────────────────────────────────

from services.tableau.connection_health import (
    build_connection_status_response,
    get_mcp_health,
    is_mcp_degraded,
)


@router.get("/connections/{conn_id}/status")
async def get_connection_status(conn_id: int, request: Request, db: Session = Depends(get_db)):
    """
    Spec 13 §3.4 T3: 获取连接 MCP 健康状态 + 数据新鲜度。
    
    Returns:
        - mcp_health: 'healthy' | 'degraded' | 'unhealthy'
        - data_freshness: {status, hours_since_sync, description}
        - connection metadata
    """
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)
    verify_connection_access(conn_id, user, db)

    conn = _db.get_connection(conn_id)
    if not conn:
        raise HTTPException(status_code=404, detail="连接不存在")

    return build_connection_status_response(conn)


@router.post("/connections/{conn_id}/sync")
async def sync_connection(
    conn_id: int,
    current_user: dict = Depends(require_roles(["admin", "data_admin"])),
    db: Session = Depends(get_db),
):
    """
    Spec 13 §3.4 T2: 触发 Tableau 资产同步（Celery 异步任务）。
    
    degraded 状态下返回 503 Service Unavailable。
    """
    _db = TableauDatabase(session=db)

    verify_connection_access(conn_id, current_user, db)

    conn = _db.get_connection(conn_id)
    if not conn:
        raise HTTPException(status_code=404, detail="连接不存在")

    # Spec 13 §3.4 T2: 检查 MCP 是否 degraded
    mcp_url = getattr(conn, 'mcp_server_url', None) or conn.server_url
    if is_mcp_degraded(mcp_url):
        raise HTTPException(
            status_code=503,
            detail={
                "error_code": "MCP_003",
                "message": "MCP 服务不可用（degraded 状态），同步操作暂停。请等待服务恢复。",
                "mcp_health": get_mcp_health(mcp_url).value,
            },
        )

    if conn.sync_status == "running":
        return {"message": "同步正在进行中", "status": "running"}

    from services.tasks import celery_app
    celery_available = False
    try:
        pong = celery_app.control.inspect(timeout=1.0).ping()
        celery_available = bool(pong)
    except Exception:
        celery_available = False

    _db.set_sync_status(conn_id, "running")

    from datetime import datetime
    from services.tasks.models import BiSyncTask

    sync_task = BiSyncTask(
        schedule_id=None,
        connection_id=conn_id,
        scheduled_at=datetime.now(),
        status="pending",
        trigger_type="manual",
    )
    db.add(sync_task)
    db.commit()
    db.refresh(sync_task)

    if celery_available:
        from services.tasks.tableau_tasks import sync_connection_task
        task = sync_connection_task.apply_async(
            args=[conn_id],
            kwargs={"trigger_type": "manual", "sync_task_id": sync_task.id},
            headers={
                "trigger_type": "manual",
                "triggered_by": current_user["id"],
            },
        )
        log_action(current_user["id"], current_user.get("username", ""), "sync", "tableau_connection", conn_id,
                   after_state={"task_id": task.id, "mode": "celery"})
        return {"task_id": task.id, "message": "同步任务已提交", "status": "pending"}

    # Celery 不可用时回退到同步执行（开发环境兼容）
    import asyncio

    def _run_sync_inline():
        from services.tableau.sync_service import TableauSyncService, TableauRestSyncService
        from services.tableau.models import TableauDatabase, TableauSyncLog, TableauConnection
        from app.core.crypto import get_tableau_crypto
        from app.core.database import get_db_context

        with get_db_context() as sync_db:
            sync_dbw = TableauDatabase(session=sync_db)
            sync_conn = sync_dbw.get_connection(conn_id)
            if not sync_conn:
                return {"status": "error", "message": "连接不存在"}

            sync_log = sync_dbw.create_sync_log(conn_id, trigger_type="manual")
            sync_dbw.set_sync_status(conn_id, "running")

            crypto = get_tableau_crypto()
            try:
                token = crypto.decrypt(sync_conn.token_encrypted)
            except Exception as e:
                msg = f"Token 解密失败: {e}"
                sync_dbw.finish_sync_log(sync_log.id, "failed", error_message=msg)
                sync_dbw.set_sync_status(conn_id, "failed")
                return {"status": "error", "message": msg}

            if getattr(sync_conn, "connection_type", "mcp") == "mcp":
                service = TableauRestSyncService(
                    server_url=sync_conn.server_url, site=sync_conn.site,
                    token_name=sync_conn.token_name, token_value=token,
                    api_version=sync_conn.api_version,
                )
            else:
                service = TableauSyncService(
                    server_url=sync_conn.server_url, site=sync_conn.site,
                    token_name=sync_conn.token_name, token_value=token,
                    api_version=sync_conn.api_version,
                )

            try:
                if not service.connect():
                    msg = "连接 Tableau Server 失败，请检查配置"
                    sync_dbw.finish_sync_log(sync_log.id, "failed", error_message=msg)
                    sync_dbw.set_sync_status(conn_id, "failed")
                    return {"status": "error", "message": msg}

                result = service.sync_all_assets(sync_dbw, conn_id, trigger_type="manual", sync_log_id=sync_log.id)
                sync_dbw.reset_sync_failures(conn_id)
                return {"status": result["status"], "total": result["total"], "sync_log_id": sync_log.id}
            except Exception as e:
                msg = str(e)
                sync_dbw.finish_sync_log(sync_log.id, "failed", error_message=msg)
                sync_dbw.set_sync_status(conn_id, "failed")
                return {"status": "error", "message": msg, "sync_log_id": sync_log.id}
            finally:
                service.disconnect()

    result = await asyncio.to_thread(_run_sync_inline)
    sync_task.status = "failed" if result.get("status") == "error" else "completed"
    sync_task.sync_log_id = result.get("sync_log_id")
    sync_task.error_message = result.get("message") if result.get("status") == "error" else None
    sync_task.updated_at = datetime.now()
    db.commit()
    if result.get("status") == "error":
        raise HTTPException(status_code=500, detail={"message": result["message"]})
    log_action(current_user["id"], current_user.get("username", ""), "sync", "tableau_connection", conn_id)
    return {
        "message": f"同步已完成，共处理 {result.get('total', 0)} 个资产",
        "status": "completed",
        "total": result.get("total", 0),
    }


@router.get("/worker-health")
async def check_worker_health(
    current_user: dict = Depends(require_roles(["admin", "data_admin"])),
):
    """检查 Celery worker 是否在线"""
    from services.tasks import celery_app
    try:
        pong = celery_app.control.inspect(timeout=1.0).ping()
        if pong:
            return {"available": True, "workers": len(pong)}
        return {"available": False, "workers": 0}
    except Exception:
        return {"available": False, "workers": 0}


# --- Asset Hierarchy (Phase 2a) ---

@router.get("/assets/{asset_id}/children")
async def get_asset_children(asset_id: int, request: Request, db: Session = Depends(get_db)):
    """获取 workbook 下属的 view/dashboard"""
    user = get_current_user(request, db) # 传递 db
    _db = TableauDatabase(session=db)

    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(status_code=404, detail="资产不存在")
    verify_connection_access(asset.connection_id, user, db)

    if asset.asset_type != "workbook":
        return {"children": []}

    children = _db.get_children_assets(asset.tableau_id, asset.connection_id)
    return {"children": [c.to_dict() for c in children]}


@router.get("/assets/{asset_id}/parent")
async def get_asset_parent(asset_id: int, request: Request, db: Session = Depends(get_db)):
    """获取 view/dashboard 的父 workbook"""
    user = get_current_user(request, db) # 传递 db
    _db = TableauDatabase(session=db)

    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(status_code=404, detail="资产不存在")
    verify_connection_access(asset.connection_id, user, db)

    parent = _db.get_parent_asset(asset_id)
    return {"parent": parent.to_dict() if parent else None}


# --- Deep AI Explain (Phase 2a) ---

class ExplainRequest(BaseModel):
    refresh: bool = False


@router.get("/assets/{asset_id}/fields")
async def get_asset_fields(asset_id: int, request: Request, db: Session = Depends(get_db)):
    """获取资产字段元数据（独立于 AI 解读）"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)
    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(status_code=404, detail="资产不存在")
    verify_connection_access(asset.connection_id, user, db)

    fields = _db.get_datasource_fields(asset_id)
    total = len(fields or [])
    cache_status = "cached" if total else "empty"
    return _fields_response_payload(fields, cache_status=cache_status, source="mcp_cache")


@router.post("/assets/{asset_id}/explain")
async def explain_asset(asset_id: int, req: ExplainRequest, request: Request, db: Session = Depends(get_db)):
    """生成/获取深度 AI 解读"""
    user = get_current_user(request, db) # 传递 db
    _db = TableauDatabase(session=db)

    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(status_code=404, detail="资产不存在")
    verify_connection_access(asset.connection_id, user, db)

    # 获取数据源字段元数据（用于 field_semantics，无论是否缓存都需要）
    fields = _db.get_datasource_fields(asset_id)
    field_semantics = []
    if fields:
        for f in fields:
            field_semantics.append({
                "field": f.field_name,
                "caption": f.ai_caption or f.field_caption or "",
                "role": f.role or "",
                "data_type": f.data_type or "",
                "meaning": f.ai_description or f.description or "",
            })

    # 缓存：1 小时内不重新生成（除非强制刷新）
    if not req.refresh and asset.ai_explain and asset.ai_explain_at:
        from datetime import datetime, timedelta  # 局部导入
        if datetime.now() - asset.ai_explain_at < timedelta(hours=1):
            return {
                "explain": asset.ai_explain,
                "cached": True,
                "generated_at": asset.ai_explain_at.strftime("%Y-%m-%d %H:%M:%S"),
                "field_semantics": field_semantics,
            }

    # 获取关联数据源信息
    datasources = _db.get_asset_datasources(asset_id)
    ds_text = "\n".join([f"- {ds.datasource_name} ({ds.datasource_type or '未知类型'})" for ds in datasources]) or "无"

    # 构建字段文本用于 prompt
    field_text = "暂无字段元数据"
    if fields:
        field_lines = []
        for f in fields:
            caption = f.ai_caption or f.field_caption or ""
            desc = f.ai_description or f.description or ""
            role_str = f.role or ""
            line = f"- {f.field_name}"
            if caption:
                line += f" ({caption})"
            line += f" [{f.data_type or ''}] [{role_str}]"
            if f.formula:
                line += f" 公式: {f.formula}"
            if desc:
                line += f" — {desc}"
            field_lines.append(line)
        field_text = "\n".join(field_lines)

    # 获取父工作簿信息
    parent_info = "无"
    if asset.parent_workbook_name:
        parent_info = asset.parent_workbook_name

    # 调用 LLM 生成深度解读
    try:
        from services.llm.prompts import ASSET_EXPLAIN_TEMPLATE
        from services.llm.service import LLMService
        llm = LLMService()

        prompt = ASSET_EXPLAIN_TEMPLATE.format(
            name=asset.name,
            asset_type=asset.asset_type,
            project_name=asset.project_name or "未分类",
            description=asset.description or "无",
            owner_name=asset.owner_name or "未知",
            parent_workbook_info=parent_info,
            datasources=ds_text,
            field_metadata=field_text,
        )

        result = await llm.complete(prompt, system="你是一个专业的 BI 报表解读专家。", timeout=30)
        if isinstance(result, dict) and "error" in result:
            return {"explain": None, "error": result["error"], "cached": False, "field_semantics": field_semantics}

        explain_text = result if isinstance(result, str) else result.get("content", str(result))
        _db.update_asset_explain(asset_id, explain_text)

        return {
            "explain": explain_text,
            "cached": False,
            "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "field_semantics": field_semantics,
        }

    except ImportError:
        return {"explain": None, "error": "LLM 服务未配置", "cached": False, "field_semantics": field_semantics}
    except Exception as e:
        return {"explain": None, "error": f"生成失败: {str(e)}", "cached": False, "field_semantics": field_semantics}


# --- Asset Chat (SPEC 41) ---

class AssetChatRequest(BaseModel):
    message: str
    connection_id: int
    history: List[dict] = []
    context: dict = {}


def _sse_frame(event: dict) -> str:
    return f"data: {json.dumps(event, ensure_ascii=False)}\n\n"


async def _generate_chat_events(
    body: AssetChatRequest,
    current_user: dict,
    db: Session,
) -> AsyncGenerator[str, None]:
    """生成资产对话 SSE 事件流"""
    from services.tableau.asset_chat_service import AssetChatService

    service = AssetChatService(db)
    try:
        async for frame in service.stream_chat(
            message=body.message,
            connection_id=body.connection_id,
            history=body.history,
            context=body.context,
        ):
            yield _sse_frame(frame)
    except Exception as exc:
        logger.error("资产对话流式生成失败: %s", exc, exc_info=True)
        yield _sse_frame({"type": "error", "code": "TAB_AC_002", "message": "对话服务暂时不可用"})


@router.post("/assets/chat")
async def chat_about_assets(
    body: AssetChatRequest,
    request: Request,
    current_user: dict = Depends(require_roles(["admin", "data_admin", "analyst"])),
    db: Session = Depends(get_db),
):
    """POST /api/tableau/assets/chat — 资产对话（SSE 流式，SPEC 41）

    鉴权要求：analyst+ 角色
    connection_id 无效或无权限时返回 403（非 SSE）
    """
    # 权限校验：验证 connection_id 是否有效且当前用户有访问权
    try:
        verify_connection_access(body.connection_id, current_user, db)
    except HTTPException:
        raise HTTPException(
            status_code=403,
            detail={"error_code": "TAB_AC_001", "message": "connection_id 无效或无权限"},
        )

    return StreamingResponse(
        _generate_chat_events(body, current_user, db),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


# --- Asset Health Score (Phase 2b) ---

@router.get("/assets/{asset_id}/health")
async def get_asset_health(asset_id: int, request: Request, db: Session = Depends(get_db)):
    """获取资产健康评分"""
    user = get_current_user(request, db) # 传递 db
    _db = TableauDatabase(session=db)
    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(status_code=404, detail="资产不存在")
    verify_connection_access(asset.connection_id, user, db)


    from services.tableau.health import compute_asset_health

    datasources = _db.get_asset_datasources(asset_id)
    fields = _db.get_datasource_fields(asset_id)
    result = compute_asset_health(asset.to_dict(), datasources, fields)

    _db.update_asset_health(asset.id, result["score"], result) # JSONB 字段直接传入 dict

    return result


@router.get("/connections/{conn_id}/health-overview")
async def get_connection_health_overview(conn_id: int, request: Request, db: Session = Depends(get_db)):
    """连接级健康总览"""
    user = get_current_user(request, db) # 传递 db
    _db = TableauDatabase(session=db)
    conn = _db.get_connection(conn_id)
    if not conn:
        raise HTTPException(status_code=404, detail="连接不存在")
    verify_connection_access(conn_id, user, db)


    from services.tableau.health import compute_asset_health, get_health_level
    from datetime import datetime, timezone

    checked_at = datetime.now(timezone.utc).isoformat()

    assets, total = _db.get_assets(conn_id, include_deleted=False, page=1, page_size=9999)
    asset_ids = [asset.id for asset in assets]
    datasources_by_asset = _db.get_asset_datasources_bulk(asset_ids)
    fields_by_asset = _db.get_datasource_fields_bulk(asset_ids)
    health_by_asset = {}
    results = []
    total_score = 0.0
    level_counts = {"excellent": 0, "good": 0, "warning": 0, "poor": 0}
    top_issues = {}

    for asset in assets:
        datasources = datasources_by_asset.get(asset.id, [])
        fields = fields_by_asset.get(asset.id, [])
        health = compute_asset_health(asset.to_dict(), datasources, fields)
        health_by_asset[asset.id] = health
        total_score += health["score"]
        level_counts[health["level"]] += 1

        failed_checks = []
        for check in health["checks"]:
            if not check["passed"]:
                top_issues[check["key"]] = top_issues.get(check["key"], 0) + 1
                failed_checks.append(check["key"])

        results.append({
            "asset_id": asset.id,
            "name": asset.name,
            "asset_type": asset.asset_type,
            "score": health["score"],
            "level": health["level"],
            "failed_checks": failed_checks,
            "checked_at": checked_at,
        })

    _db.update_assets_health_bulk(health_by_asset)

    avg_score = round(total_score / len(assets), 1) if assets else 0
    sorted_issues = sorted(top_issues.items(), key=lambda x: x[1], reverse=True)

    return {
        "connection_id": conn_id,
        "connection_name": conn.name,
        "total_assets": len(assets),
        "avg_score": avg_score,
        "avg_level": get_health_level(avg_score),
        "level_distribution": level_counts,
        "top_issues": [{"check": k, "count": v} for k, v in sorted_issues[:5]],
        "assets": sorted(results, key=lambda x: x["score"]),
    }


# ── Tableau MCP Server 状态检查 ─────────────────────────────────────────────

import asyncio as _asyncio
import time as _time

try:
    import httpx as _httpx
except ImportError:
    _httpx = None  # type: ignore

from services.common.settings import get_tableau_mcp_server_url, get_tableau_mcp_timeout


@router.get("/mcp-status")
async def get_mcp_status():
    """探测 Tableau MCP Server 连通性（UI 状态指示器用）"""
    url = get_tableau_mcp_server_url()
    timeout = min(get_tableau_mcp_timeout(), 5)
    if _httpx is None:
        return {"status": "unknown", "url": url, "latency_ms": 0, "error": "httpx not installed"}

    for attempt in range(2):
        start = _time.monotonic()
        try:
            async with _httpx.AsyncClient(timeout=timeout) as client:
                resp = await client.get(url)
            return {
                "status": "online",
                "url": url,
                "latency_ms": int((_time.monotonic() - start) * 1000),
                "http_status": resp.status_code,
                **({"retried": True} if attempt == 1 else {}),
            }
        except _httpx.TimeoutException as e:
            return {
                "status": "offline",
                "url": url,
                "latency_ms": int((_time.monotonic() - start) * 1000),
                "error": type(e).__name__,
            }
        except _httpx.ConnectError as e:
            if attempt == 0:
                await _asyncio.sleep(1)  # 参考 Spec 22 _post_mcp：ConnectError 重试 1 次间隔 1s
                continue
            return {
                "status": "offline",
                "url": url,
                "latency_ms": int((_time.monotonic() - start) * 1000),
                "error": type(e).__name__,
                "retried": True,
            }


# ── V2: Tableau MCP Direct Connect REST Endpoints ────────────────────────────

from services.tableau.mcp_client import (
    TableauMCPError,
    extract_datasource_metadata_fields,
    get_tableau_mcp_client,
    normalize_datasource_metadata_field,
)
from services.tableau.models import TableauDatabase, TableauSyncLog
from services.tableau.models import TableauConnection as TableauConnectionModel


class VizQLQueryRequest(BaseModel):
    """简化的 VizQL 查询结构"""
    measures: list[dict] = []
    dimensions: list[dict] = []
    filters: list[dict] = []
    limit: int = 100


class TableauQueryRequest(BaseModel):
    connection_id: int
    datasource_luid: str
    vizql: VizQLQueryRequest
    timeout: int = 30


def _build_vizql_query(vizql: VizQLQueryRequest) -> dict:
    """将简化 VizQL 结构转换为 MCP query-datasource 格式"""
    fields = []
    for m in vizql.measures:
        f = {"fieldCaption": m["field"]}
        if m.get("aggregation"):
            f["function"] = m["aggregation"]
        if m.get("alias"):
            f["fieldAlias"] = m["alias"]
        fields.append(f)
    for d in vizql.dimensions:
        f = {"fieldCaption": d["field"]}
        if d.get("alias"):
            f["fieldAlias"] = d["alias"]
        fields.append(f)
    query = {"fields": fields}
    if vizql.filters:
        query["filters"] = vizql.filters
    return query


def _mcp_error_response(exc: TableauMCPError) -> tuple[int, dict]:
    """将 TableauMCPError 映射为 HTTP 状态码 + 错误体"""
    code_map = {
        "NLQ_006": "MCP_003",
        "NLQ_007": "MCP_004",
        "NLQ_009": "MCP_005",
        "MCP_010": "MCP_006",
    }
    http_status = {
        "MCP_003": 503,
        "MCP_004": 504,
        "MCP_005": 401,
        "MCP_006": 400,
    }.get(code_map.get(exc.code, ""), 503)
    return http_status, {
        "error_code": code_map.get(exc.code, "MCP_001"),
        "message": exc.message,
    }


@router.post("/query")
async def tableau_v2_query(
    req: TableauQueryRequest,
    request: Request,
    db: Session = Depends(get_db),
):
    """V2-1: MCP Direct Connect — 执行 VizQL 查询"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    verify_connection_access(req.connection_id, user, db)
    conn = _db.get_connection(req.connection_id)
    if not conn:
        raise HTTPException(status_code=404, detail="连接不存在")

    if not getattr(conn, "mcp_direct_enabled", False):
        raise HTTPException(
            status_code=400,
            detail={"error_code": "MCP_010", "message": "连接未开启 V2 直连模式，请使用 V1 API"},
        )

    vizql_query = _build_vizql_query(req.vizql)

    try:
        client = get_tableau_mcp_client(req.connection_id)
        result = client.query_datasource(
            datasource_luid=req.datasource_luid,
            query=vizql_query,
            limit=min(req.vizql.limit, 10000),
            timeout=req.timeout,
            connection_id=req.connection_id,
        )

        # 解析 MCP 返回：{"fields": [...], "rows": [[...]], ...}
        raw_fields = result.get("fields", [])
        raw_rows = result.get("rows", [])

        # 映射为统一列定义
        columns = []
        for f in raw_fields:
            name = f.get("fieldAlias") or f.get("fieldCaption") or f.get("fieldName", "?")
            columns.append({"name": name, "dataType": f.get("dataType", "STRING")})

        return {
            "columns": columns,
            "rows": raw_rows,
            "row_count": len(raw_rows),
            "truncated": result.get("truncated", False),
            "datasource_luid": req.datasource_luid,
            "executed_at": _time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime()),
        }

    except TableauMCPError as e:
        status, body = _mcp_error_response(e)
        raise HTTPException(status_code=status, detail=body)


# ── SPEC 39: 资产意图搜索 ─────────────────────────────────────────────────────

class IntentSearchRequest(BaseModel):
    query: str
    connection_id: str


@router.post("/assets/intent-search")
async def intent_search_assets(
    body: IntentSearchRequest,
    current_user: dict = Depends(require_roles(["admin", "data_admin", "analyst"])),
    db: Session = Depends(get_db),
):
    """自然语言意图搜索（SPEC 39）

    权限：admin / data_admin / analyst
    """
    query = body.query[:200]
    connection_id = body.connection_id

    # 验证 connection_id：必须是整数 ID（tableau_connections.id 为 Integer），校验权限
    try:
        conn_id_int = int(connection_id)
    except (ValueError, TypeError):
        raise HTTPException(
            status_code=403,
            detail={"error_code": "TAB_IS_002", "message": "connection_id 无效或无权访问"},
        )
    verify_connection_access(conn_id_int, current_user, db)

    from services.tableau.intent_search_service import IntentSearchService

    service = IntentSearchService(db=db)
    try:
        result = await service.intent_search(query=query, connection_id=conn_id_int)
        return result
    except Exception as e:
        logger.error("intent_search 失败: %s", e, exc_info=True)
        raise HTTPException(
            status_code=500,
            detail={"error_code": "TAB_IS_001", "message": "意图解析失败，请重试"},
        )


# ── SPEC 40: 资产影响分析 ─────────────────────────────────────────────────────

@router.get("/assets/{asset_id}/impact")
async def get_asset_impact(
    asset_id: int,
    request: Request,
    db: Session = Depends(get_db),
):
    """SPEC 40: 查询 datasource 资产的两级影响树（仅 datasource 类型）"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(
            status_code=400,
            detail={"error_code": "TAB_IA_001", "message": "资产不存在或类型不是 datasource", "detail": {}},
        )

    verify_connection_access(asset.connection_id, user, db)

    if asset.asset_type != "datasource":
        raise HTTPException(
            status_code=400,
            detail={"error_code": "TAB_IA_001", "message": "资产不存在或类型不是 datasource", "detail": {}},
        )

    from services.tableau.impact_service import ImpactService
    svc = ImpactService(db=db)
    try:
        result = svc.get_asset_impact(asset_id)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail={"error_code": "TAB_IA_001", "message": "资产不存在或类型不是 datasource", "detail": {}},
        )
    return result


@router.get("/connections/{conn_id}/impact-alerts")
async def get_impact_alerts(
    conn_id: int,
    request: Request,
    db: Session = Depends(get_db),
):
    """SPEC 40: 查询连接级健康预警（health_score < 60 的 datasource）"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    conn = _db.get_connection(conn_id)
    if not conn:
        raise HTTPException(status_code=404, detail="连接不存在")

    verify_connection_access(conn_id, user, db)

    from services.tableau.impact_service import ImpactService
    svc = ImpactService(db=db)
    return svc.get_impact_alerts(conn_id)


@router.get("/datasources/{asset_id}/metadata")
async def tableau_v2_metadata(
    asset_id: int,
    request: Request,
    refresh: bool = False,
    db: Session = Depends(get_db),
):
    """V2-2: 获取数据源字段元数据（带缓存）"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(status_code=404, detail="资产不存在")
    if asset.asset_type != "datasource":
        raise HTTPException(
            status_code=400,
            detail={"error_code": "MCP_010", "message": "该资产不是 datasource 类型"},
        )

    verify_connection_access(asset.connection_id, user, db)
    conn = _db.get_connection(asset.connection_id)
    if not conn:
        raise HTTPException(status_code=404, detail="连接不存在")

    cached_fields = _db.get_datasource_fields(asset_id)
    now = _time.time()
    cache_ttl = 24 * 3600  # 24h

    def _metadata_response(fields, *, cache_status: str, cached_at: Optional[str]):
        return _fields_response_payload(
            fields,
            cache_status=cache_status,
            source="mcp_cache",
            datasource_luid=asset.tableau_id,
            cached_at=cached_at,
        )

    # 缓存命中且未过期
    if cached_fields and not refresh:
        oldest = min((f.fetched_at.timestamp() for f in cached_fields), default=0)
        if now - oldest < cache_ttl:
            return _metadata_response(
                cached_fields,
                cache_status="cached",
                cached_at=_time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime(oldest)),
            )

    # 需要拉取（首次 or refresh=true）
    try:
        client = get_tableau_mcp_client(asset.connection_id)
        raw = client.get_datasource_metadata(asset.tableau_id, timeout=30)
        raw_fields = extract_datasource_metadata_fields(raw)

        # 写入缓存
        if raw_fields:
            parsed = [normalize_datasource_metadata_field(f) for f in raw_fields]
            _db.upsert_datasource_fields(asset.id, asset.tableau_id, parsed)
            try:
                from services.tableau.field_reconciliation import TableauFieldReconciliationService

                TableauFieldReconciliationService(db).reconcile_asset(
                    asset_id=asset.id,
                    connection_id=asset.connection_id,
                    datasource_luid=asset.tableau_id,
                    metadata=raw,
                )
            except Exception:
                logger.warning(
                    "Tableau MCP metadata reconciliation skipped after refresh: asset_id=%s datasource_luid=%s",
                    asset.id,
                    asset.tableau_id,
                    exc_info=True,
                )
        else:
            logger.warning(
                "Tableau MCP metadata refresh returned no parseable fields: asset_id=%s datasource_luid=%s raw_keys=%s",
                asset.id,
                asset.tableau_id,
                list(raw.keys()) if isinstance(raw, dict) else type(raw).__name__,
            )
            if cached_fields:
                oldest = min((f.fetched_at.timestamp() for f in cached_fields), default=0)
                return _metadata_response(
                    cached_fields,
                    cache_status="stale",
                    cached_at=_time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime(oldest)),
                )
            raise HTTPException(
                status_code=502,
                detail={
                    "error_code": "MCP_011",
                    "message": "MCP 返回了元数据但未解析出字段",
                },
            )

        # 重新读取（包含新数据）
        cached_fields = _db.get_datasource_fields(asset_id)
        oldest = min((f.fetched_at.timestamp() for f in cached_fields), default=0)
        return _metadata_response(
            cached_fields,
            cache_status="fresh",
            cached_at=_time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime(oldest)) if cached_fields else None,
        )

    except TableauMCPError:
        # MCP 不可达，降级返回缓存数据
        if cached_fields:
            oldest = min((f.fetched_at.timestamp() for f in cached_fields), default=0)
            return _metadata_response(
                cached_fields,
                cache_status="stale",
                cached_at=_time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime(oldest)),
            )
        raise HTTPException(
            status_code=503,
            detail={"error_code": "MCP_003", "message": "MCP Server 不可达，且无缓存数据"},
        )


@router.get("/datasources/{asset_id}/preview")
async def tableau_v2_preview(
    asset_id: int,
    request: Request,
    limit: int = Query(20, ge=1, le=500),
    db: Session = Depends(get_db),
):
    """V2-3: 数据预览（自动选取字段）"""
    user = get_current_user(request, db)
    _db = TableauDatabase(session=db)

    asset = _db.get_asset(asset_id)
    if not asset or asset.is_deleted:
        raise HTTPException(status_code=404, detail="资产不存在")
    if asset.asset_type != "datasource":
        raise HTTPException(
            status_code=400,
            detail={"error_code": "MCP_010", "message": "该资产不是 datasource 类型"},
        )

    verify_connection_access(asset.connection_id, user, db)

    # 从缓存字段中选取前几个（dimension 优先）
    fields = _db.get_datasource_fields(asset_id)
    preview_fields = []
    for f in fields:
        if len(preview_fields) >= 10:
            break
        preview_fields.append(f)

    vizql_fields = []
    for f in preview_fields:
        vizql_fields.append({"fieldCaption": f.field_name})
        if f.role == "measure":
            vizql_fields[-1]["function"] = "NONE"

    query = {"fields": vizql_fields}

    try:
        client = get_tableau_mcp_client(asset.connection_id)
        result = client.query_datasource(
            datasource_luid=asset.tableau_id,
            query=query,
            limit=limit,
            timeout=30,
            connection_id=asset.connection_id,
        )

        raw_fields = result.get("fields", [])
        raw_rows = result.get("rows", [])
        columns = []
        for f in raw_fields:
            name = f.get("fieldAlias") or f.get("fieldCaption") or f.get("fieldName", "?")
            columns.append({"name": name, "dataType": f.get("dataType", "STRING")})

        return {
            "columns": columns,
            "rows": raw_rows,
            "row_count": len(raw_rows),
            "truncated": result.get("truncated", False),
            "datasource_luid": asset.tableau_id,
            "executed_at": _time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime()),
        }

    except TableauMCPError as e:
        status, body = _mcp_error_response(e)
        raise HTTPException(status_code=status, detail=body)
