"""事件服务模块"""
from .event_service import emit_event
from .constants import (
    ALL_EVENT_TYPES,
    TABLEAU_SYNC_COMPLETED, TABLEAU_SYNC_FAILED, TABLEAU_CONNECTION_TESTED,
    SEMANTIC_SUBMITTED, SEMANTIC_APPROVED, SEMANTIC_REJECTED,
    SEMANTIC_PUBLISHED, SEMANTIC_PUBLISH_FAILED, SEMANTIC_ROLLBACK, SEMANTIC_AI_GENERATED,
    SEMANTIC_TABLE_CREATED, SEMANTIC_TABLE_SUBMITTED,
    SEMANTIC_TABLE_PUBLISHED, SEMANTIC_TABLE_DEPRECATED,
    FIELD_SYNC_COMPLETED,
    HEALTH_SCAN_COMPLETED, HEALTH_SCAN_FAILED, HEALTH_SCORE_DROPPED,
    AUTH_USER_LOGIN, AUTH_USER_CREATED, AUTH_USER_ROLE_CHANGED,
    SYSTEM_MAINTENANCE, SYSTEM_ERROR,
    METRIC_PUBLISHED, METRIC_ANOMALY_DETECTED, METRIC_CONSISTENCY_FAILED,
    SOURCE_MODULE_TABLEAU, SOURCE_MODULE_SEMANTIC, SOURCE_MODULE_HEALTH,
    SOURCE_MODULE_AUTH, SOURCE_MODULE_SYSTEM, SOURCE_MODULE_METRICS,
    SEVERITY_INFO, SEVERITY_WARNING, SEVERITY_ERROR,
    EvtErrorCode, EVT_ERROR_MESSAGES,
)

__all__ = [
    "emit_event",
    "ALL_EVENT_TYPES",
    "TABLEAU_SYNC_COMPLETED", "TABLEAU_SYNC_FAILED", "TABLEAU_CONNECTION_TESTED",
    "SEMANTIC_SUBMITTED", "SEMANTIC_APPROVED", "SEMANTIC_REJECTED",
    "SEMANTIC_PUBLISHED", "SEMANTIC_PUBLISH_FAILED", "SEMANTIC_ROLLBACK", "SEMANTIC_AI_GENERATED",
    "SEMANTIC_TABLE_CREATED", "SEMANTIC_TABLE_SUBMITTED",
    "SEMANTIC_TABLE_PUBLISHED", "SEMANTIC_TABLE_DEPRECATED",
    "FIELD_SYNC_COMPLETED",
    "HEALTH_SCAN_COMPLETED", "HEALTH_SCAN_FAILED", "HEALTH_SCORE_DROPPED",
    "AUTH_USER_LOGIN", "AUTH_USER_CREATED", "AUTH_USER_ROLE_CHANGED",
    "SYSTEM_MAINTENANCE", "SYSTEM_ERROR",
    "METRIC_PUBLISHED", "METRIC_ANOMALY_DETECTED", "METRIC_CONSISTENCY_FAILED",
    "SOURCE_MODULE_TABLEAU", "SOURCE_MODULE_SEMANTIC", "SOURCE_MODULE_HEALTH",
    "SOURCE_MODULE_AUTH", "SOURCE_MODULE_SYSTEM", "SOURCE_MODULE_METRICS",
    "SEVERITY_INFO", "SEVERITY_WARNING", "SEVERITY_ERROR",
]